package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AbonoLiquidacion generated by hbm2java
 */
@Entity
@Table(name="abono_liquidacion"
    ,catalog="sigf_v1"
)
public class AbonoLiquidacion  implements java.io.Serializable {


     private int idAbonoLiquidacion;
     private AbonoBus abonoBus;
     private LiquidacionEmpresa liquidacionEmpresa;
     private int montoAbono;

    public AbonoLiquidacion() {
    }

    public AbonoLiquidacion(int idAbonoLiquidacion, AbonoBus abonoBus, LiquidacionEmpresa liquidacionEmpresa, int montoAbono) {
       this.idAbonoLiquidacion = idAbonoLiquidacion;
       this.abonoBus = abonoBus;
       this.liquidacionEmpresa = liquidacionEmpresa;
       this.montoAbono = montoAbono;
    }
   
     @Id 

    
    @Column(name="id_abono_liquidacion", unique=true, nullable=false)
    public int getIdAbonoLiquidacion() {
        return this.idAbonoLiquidacion;
    }
    
    public void setIdAbonoLiquidacion(int idAbonoLiquidacion) {
        this.idAbonoLiquidacion = idAbonoLiquidacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_abono_bus", nullable=false)
    public AbonoBus getAbonoBus() {
        return this.abonoBus;
    }
    
    public void setAbonoBus(AbonoBus abonoBus) {
        this.abonoBus = abonoBus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_liquidacion_empresa", nullable=false)
    public LiquidacionEmpresa getLiquidacionEmpresa() {
        return this.liquidacionEmpresa;
    }
    
    public void setLiquidacionEmpresa(LiquidacionEmpresa liquidacionEmpresa) {
        this.liquidacionEmpresa = liquidacionEmpresa;
    }

    
    @Column(name="monto_abono", nullable=false)
    public int getMontoAbono() {
        return this.montoAbono;
    }
    
    public void setMontoAbono(int montoAbono) {
        this.montoAbono = montoAbono;
    }




}


