package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AdministracionMensual generated by hbm2java
 */
@Entity
@Table(name="administracion_mensual"
    ,catalog="sigf_v1"
)
public class AdministracionMensual  implements java.io.Serializable {


     private Integer idAdministracionMensual;
     private int mes;
     private int anio;
     private int valor;
     private Set<DetalleIntervalosMensual> detalleIntervalosMensuals = new HashSet<DetalleIntervalosMensual>(0);

    public AdministracionMensual() {
    }

	
    public AdministracionMensual(int mes, int anio, int valor) {
        this.mes = mes;
        this.anio = anio;
        this.valor = valor;
    }
    public AdministracionMensual(int mes, int anio, int valor, Set<DetalleIntervalosMensual> detalleIntervalosMensuals) {
       this.mes = mes;
       this.anio = anio;
       this.valor = valor;
       this.detalleIntervalosMensuals = detalleIntervalosMensuals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_administracion_mensual", unique=true, nullable=false)
    public Integer getIdAdministracionMensual() {
        return this.idAdministracionMensual;
    }
    
    public void setIdAdministracionMensual(Integer idAdministracionMensual) {
        this.idAdministracionMensual = idAdministracionMensual;
    }

    
    @Column(name="mes", nullable=false)
    public int getMes() {
        return this.mes;
    }
    
    public void setMes(int mes) {
        this.mes = mes;
    }

    
    @Column(name="anio", nullable=false)
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }

    
    @Column(name="valor", nullable=false)
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="administracionMensual")
    public Set<DetalleIntervalosMensual> getDetalleIntervalosMensuals() {
        return this.detalleIntervalosMensuals;
    }
    
    public void setDetalleIntervalosMensuals(Set<DetalleIntervalosMensual> detalleIntervalosMensuals) {
        this.detalleIntervalosMensuals = detalleIntervalosMensuals;
    }




}


