package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AnticipoTrabajador generated by hbm2java
 */
@Entity
@Table(name="anticipo_trabajador"
    ,catalog="sigf_v1"
)
public class AnticipoTrabajador  implements java.io.Serializable {


     private Integer idAnticipoTrabajador;
     private Trabajador trabajador;
     private int mes;
     private int anio;
     private int monto;

    public AnticipoTrabajador() {
    }

    public AnticipoTrabajador(Trabajador trabajador, int mes, int anio, int monto) {
       this.trabajador = trabajador;
       this.mes = mes;
       this.anio = anio;
       this.monto = monto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_anticipo_trabajador", unique=true, nullable=false)
    public Integer getIdAnticipoTrabajador() {
        return this.idAnticipoTrabajador;
    }
    
    public void setIdAnticipoTrabajador(Integer idAnticipoTrabajador) {
        this.idAnticipoTrabajador = idAnticipoTrabajador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_trabajador", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    
    @Column(name="mes", nullable=false)
    public int getMes() {
        return this.mes;
    }
    
    public void setMes(int mes) {
        this.mes = mes;
    }

    
    @Column(name="anio", nullable=false)
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }

    
    @Column(name="monto", nullable=false)
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }




}


