package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BusDevice generated by hbm2java
 */
@Entity
@Table(name="bus_device"
    ,catalog="sigf_v1"
)
public class BusDevice  implements java.io.Serializable {


     private Integer idBusDevice;
     private Bus bus;
     private Device device;
     private Date fechaRegistro;

    public BusDevice() {
    }

    public BusDevice(Bus bus, Device device, Date fechaRegistro) {
       this.bus = bus;
       this.device = device;
       this.fechaRegistro = fechaRegistro;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_bus_device", unique=true, nullable=false)
    public Integer getIdBusDevice() {
        return this.idBusDevice;
    }
    
    public void setIdBusDevice(Integer idBusDevice) {
        this.idBusDevice = idBusDevice;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_bus", nullable=false)
    public Bus getBus() {
        return this.bus;
    }
    
    public void setBus(Bus bus) {
        this.bus = bus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_device", nullable=false)
    public Device getDevice() {
        return this.device;
    }
    
    public void setDevice(Device device) {
        this.device = device;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_registro", nullable=false, length=10)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


