package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CalleServicio generated by hbm2java
 */
@Entity
@Table(name="calle_servicio"
    ,catalog="sigf_v1"
)
public class CalleServicio  implements java.io.Serializable {


     private Integer idCalleServicio;
     private Calle calle;
     private Servicio servicio;
     private int numeroOrden;
     private Boolean sentido;

    public CalleServicio() {
    }

	
    public CalleServicio(Calle calle, Servicio servicio, int numeroOrden) {
        this.calle = calle;
        this.servicio = servicio;
        this.numeroOrden = numeroOrden;
    }
    public CalleServicio(Calle calle, Servicio servicio, int numeroOrden, Boolean sentido) {
       this.calle = calle;
       this.servicio = servicio;
       this.numeroOrden = numeroOrden;
       this.sentido = sentido;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_calle_servicio", unique=true, nullable=false)
    public Integer getIdCalleServicio() {
        return this.idCalleServicio;
    }
    
    public void setIdCalleServicio(Integer idCalleServicio) {
        this.idCalleServicio = idCalleServicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_calle", nullable=false)
    public Calle getCalle() {
        return this.calle;
    }
    
    public void setCalle(Calle calle) {
        this.calle = calle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_servicio", nullable=false)
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }

    
    @Column(name="numero_orden", nullable=false)
    public int getNumeroOrden() {
        return this.numeroOrden;
    }
    
    public void setNumeroOrden(int numeroOrden) {
        this.numeroOrden = numeroOrden;
    }

    
    @Column(name="sentido")
    public Boolean getSentido() {
        return this.sentido;
    }
    
    public void setSentido(Boolean sentido) {
        this.sentido = sentido;
    }




}


