package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CargaRetroactiva generated by hbm2java
 */
@Entity
@Table(name="carga_retroactiva"
    ,catalog="sigf_v1"
)
public class CargaRetroactiva  implements java.io.Serializable {


     private Integer idCargaRetroactiva;
     private CargasTrabajador cargasTrabajador;
     private Trabajador trabajador;
     private int mesLiquidacion;
     private int anioLiquidacion;
     private int montoRetroactivo;

    public CargaRetroactiva() {
    }

    public CargaRetroactiva(CargasTrabajador cargasTrabajador, Trabajador trabajador, int mesLiquidacion, int anioLiquidacion, int montoRetroactivo) {
       this.cargasTrabajador = cargasTrabajador;
       this.trabajador = trabajador;
       this.mesLiquidacion = mesLiquidacion;
       this.anioLiquidacion = anioLiquidacion;
       this.montoRetroactivo = montoRetroactivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_carga_retroactiva", unique=true, nullable=false)
    public Integer getIdCargaRetroactiva() {
        return this.idCargaRetroactiva;
    }
    
    public void setIdCargaRetroactiva(Integer idCargaRetroactiva) {
        this.idCargaRetroactiva = idCargaRetroactiva;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_carga_trabajador", nullable=false)
    public CargasTrabajador getCargasTrabajador() {
        return this.cargasTrabajador;
    }
    
    public void setCargasTrabajador(CargasTrabajador cargasTrabajador) {
        this.cargasTrabajador = cargasTrabajador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_trabajador", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    
    @Column(name="mes_liquidacion", nullable=false)
    public int getMesLiquidacion() {
        return this.mesLiquidacion;
    }
    
    public void setMesLiquidacion(int mesLiquidacion) {
        this.mesLiquidacion = mesLiquidacion;
    }

    
    @Column(name="anio_liquidacion", nullable=false)
    public int getAnioLiquidacion() {
        return this.anioLiquidacion;
    }
    
    public void setAnioLiquidacion(int anioLiquidacion) {
        this.anioLiquidacion = anioLiquidacion;
    }

    
    @Column(name="monto_retroactivo", nullable=false)
    public int getMontoRetroactivo() {
        return this.montoRetroactivo;
    }
    
    public void setMontoRetroactivo(int montoRetroactivo) {
        this.montoRetroactivo = montoRetroactivo;
    }




}


