package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CargasTrabajador generated by hbm2java
 */
@Entity
@Table(name="cargas_trabajador"
    ,catalog="sigf_v1"
)
public class CargasTrabajador  implements java.io.Serializable {


     private Integer idCargasTrabajador;
     private ParentescoCarga parentescoCarga;
     private TipoCarga tipoCarga;
     private Trabajador trabajador;
     private String apellidoCargaTrabajador;
     private String nombreCargaTrabajador;
     private String rut;
     private Date fechaNacimiento;
     private Date fechaIngreso;
     private boolean activa;
     private Set<CargaRetroactiva> cargaRetroactivas = new HashSet<CargaRetroactiva>(0);

    public CargasTrabajador() {
    }

	
    public CargasTrabajador(ParentescoCarga parentescoCarga, TipoCarga tipoCarga, Trabajador trabajador, String apellidoCargaTrabajador, String nombreCargaTrabajador, String rut, Date fechaIngreso, boolean activa) {
        this.parentescoCarga = parentescoCarga;
        this.tipoCarga = tipoCarga;
        this.trabajador = trabajador;
        this.apellidoCargaTrabajador = apellidoCargaTrabajador;
        this.nombreCargaTrabajador = nombreCargaTrabajador;
        this.rut = rut;
        this.fechaIngreso = fechaIngreso;
        this.activa = activa;
    }
    public CargasTrabajador(ParentescoCarga parentescoCarga, TipoCarga tipoCarga, Trabajador trabajador, String apellidoCargaTrabajador, String nombreCargaTrabajador, String rut, Date fechaNacimiento, Date fechaIngreso, boolean activa, Set<CargaRetroactiva> cargaRetroactivas) {
       this.parentescoCarga = parentescoCarga;
       this.tipoCarga = tipoCarga;
       this.trabajador = trabajador;
       this.apellidoCargaTrabajador = apellidoCargaTrabajador;
       this.nombreCargaTrabajador = nombreCargaTrabajador;
       this.rut = rut;
       this.fechaNacimiento = fechaNacimiento;
       this.fechaIngreso = fechaIngreso;
       this.activa = activa;
       this.cargaRetroactivas = cargaRetroactivas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cargas_trabajador", unique=true, nullable=false)
    public Integer getIdCargasTrabajador() {
        return this.idCargasTrabajador;
    }
    
    public void setIdCargasTrabajador(Integer idCargasTrabajador) {
        this.idCargasTrabajador = idCargasTrabajador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_parentesco_carga", nullable=false)
    public ParentescoCarga getParentescoCarga() {
        return this.parentescoCarga;
    }
    
    public void setParentescoCarga(ParentescoCarga parentescoCarga) {
        this.parentescoCarga = parentescoCarga;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_carga", nullable=false)
    public TipoCarga getTipoCarga() {
        return this.tipoCarga;
    }
    
    public void setTipoCarga(TipoCarga tipoCarga) {
        this.tipoCarga = tipoCarga;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_trabajador", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    
    @Column(name="apellido_carga_trabajador", nullable=false, length=45)
    public String getApellidoCargaTrabajador() {
        return this.apellidoCargaTrabajador;
    }
    
    public void setApellidoCargaTrabajador(String apellidoCargaTrabajador) {
        this.apellidoCargaTrabajador = apellidoCargaTrabajador;
    }

    
    @Column(name="nombre_carga_trabajador", nullable=false, length=45)
    public String getNombreCargaTrabajador() {
        return this.nombreCargaTrabajador;
    }
    
    public void setNombreCargaTrabajador(String nombreCargaTrabajador) {
        this.nombreCargaTrabajador = nombreCargaTrabajador;
    }

    
    @Column(name="rut", nullable=false, length=45)
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_nacimiento", length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_ingreso", nullable=false, length=10)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="activa", nullable=false)
    public boolean isActiva() {
        return this.activa;
    }
    
    public void setActiva(boolean activa) {
        this.activa = activa;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cargasTrabajador")
    public Set<CargaRetroactiva> getCargaRetroactivas() {
        return this.cargaRetroactivas;
    }
    
    public void setCargaRetroactivas(Set<CargaRetroactiva> cargaRetroactivas) {
        this.cargaRetroactivas = cargaRetroactivas;
    }




}


