package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CausalFiniquito generated by hbm2java
 */
@Entity
@Table(name="causal_finiquito"
    ,catalog="sigf_v1"
)
public class CausalFiniquito  implements java.io.Serializable {


     private int idCausalFiniquito;
     private String codigoCausalFiniquito;
     private String descripcionCausalFiniquito;
     private Set<FiniquitoRelacionLaboral> finiquitoRelacionLaborals = new HashSet<FiniquitoRelacionLaboral>(0);

    public CausalFiniquito() {
    }

	
    public CausalFiniquito(int idCausalFiniquito, String codigoCausalFiniquito, String descripcionCausalFiniquito) {
        this.idCausalFiniquito = idCausalFiniquito;
        this.codigoCausalFiniquito = codigoCausalFiniquito;
        this.descripcionCausalFiniquito = descripcionCausalFiniquito;
    }
    public CausalFiniquito(int idCausalFiniquito, String codigoCausalFiniquito, String descripcionCausalFiniquito, Set<FiniquitoRelacionLaboral> finiquitoRelacionLaborals) {
       this.idCausalFiniquito = idCausalFiniquito;
       this.codigoCausalFiniquito = codigoCausalFiniquito;
       this.descripcionCausalFiniquito = descripcionCausalFiniquito;
       this.finiquitoRelacionLaborals = finiquitoRelacionLaborals;
    }
   
     @Id 

    
    @Column(name="id_causal_finiquito", unique=true, nullable=false)
    public int getIdCausalFiniquito() {
        return this.idCausalFiniquito;
    }
    
    public void setIdCausalFiniquito(int idCausalFiniquito) {
        this.idCausalFiniquito = idCausalFiniquito;
    }

    
    @Column(name="codigo_causal_finiquito", nullable=false, length=45)
    public String getCodigoCausalFiniquito() {
        return this.codigoCausalFiniquito;
    }
    
    public void setCodigoCausalFiniquito(String codigoCausalFiniquito) {
        this.codigoCausalFiniquito = codigoCausalFiniquito;
    }

    
    @Column(name="descripcion_causal_finiquito", nullable=false, length=250)
    public String getDescripcionCausalFiniquito() {
        return this.descripcionCausalFiniquito;
    }
    
    public void setDescripcionCausalFiniquito(String descripcionCausalFiniquito) {
        this.descripcionCausalFiniquito = descripcionCausalFiniquito;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="causalFiniquito")
    public Set<FiniquitoRelacionLaboral> getFiniquitoRelacionLaborals() {
        return this.finiquitoRelacionLaborals;
    }
    
    public void setFiniquitoRelacionLaborals(Set<FiniquitoRelacionLaboral> finiquitoRelacionLaborals) {
        this.finiquitoRelacionLaborals = finiquitoRelacionLaborals;
    }




}


