package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompraBoleto generated by hbm2java
 */
@Entity
@Table(name="compra_boleto"
    ,catalog="sigf_v1"
)
public class CompraBoleto  implements java.io.Serializable {


     private Integer idCompraBoleto;
     private int folioFactura;
     private Date fechaCompraBoleto;
     private int total;
     private Set<DetalleCompraBoleto> detalleCompraBoletos = new HashSet<DetalleCompraBoleto>(0);

    public CompraBoleto() {
    }

	
    public CompraBoleto(int folioFactura, Date fechaCompraBoleto, int total) {
        this.folioFactura = folioFactura;
        this.fechaCompraBoleto = fechaCompraBoleto;
        this.total = total;
    }
    public CompraBoleto(int folioFactura, Date fechaCompraBoleto, int total, Set<DetalleCompraBoleto> detalleCompraBoletos) {
       this.folioFactura = folioFactura;
       this.fechaCompraBoleto = fechaCompraBoleto;
       this.total = total;
       this.detalleCompraBoletos = detalleCompraBoletos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_compra_boleto", unique=true, nullable=false)
    public Integer getIdCompraBoleto() {
        return this.idCompraBoleto;
    }
    
    public void setIdCompraBoleto(Integer idCompraBoleto) {
        this.idCompraBoleto = idCompraBoleto;
    }

    
    @Column(name="folio_factura", nullable=false)
    public int getFolioFactura() {
        return this.folioFactura;
    }
    
    public void setFolioFactura(int folioFactura) {
        this.folioFactura = folioFactura;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_compra_boleto", nullable=false, length=19)
    public Date getFechaCompraBoleto() {
        return this.fechaCompraBoleto;
    }
    
    public void setFechaCompraBoleto(Date fechaCompraBoleto) {
        this.fechaCompraBoleto = fechaCompraBoleto;
    }

    
    @Column(name="total", nullable=false)
    public int getTotal() {
        return this.total;
    }
    
    public void setTotal(int total) {
        this.total = total;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="compraBoleto")
    public Set<DetalleCompraBoleto> getDetalleCompraBoletos() {
        return this.detalleCompraBoletos;
    }
    
    public void setDetalleCompraBoletos(Set<DetalleCompraBoleto> detalleCompraBoletos) {
        this.detalleCompraBoletos = detalleCompraBoletos;
    }




}


