package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ControlServicio generated by hbm2java
 */
@Entity
@Table(name="control_servicio"
    ,catalog="sigf_v1"
)
public class ControlServicio  implements java.io.Serializable {


     private Integer idControlServicio;
     private Control control;
     private Servicio servicio;
     private Date tiempo;
     private int numeroOrden;
     private Set<ControlHorarioServicio> controlHorarioServicios = new HashSet<ControlHorarioServicio>(0);

    public ControlServicio() {
    }

	
    public ControlServicio(Control control, Servicio servicio, Date tiempo, int numeroOrden) {
        this.control = control;
        this.servicio = servicio;
        this.tiempo = tiempo;
        this.numeroOrden = numeroOrden;
    }
    public ControlServicio(Control control, Servicio servicio, Date tiempo, int numeroOrden, Set<ControlHorarioServicio> controlHorarioServicios) {
       this.control = control;
       this.servicio = servicio;
       this.tiempo = tiempo;
       this.numeroOrden = numeroOrden;
       this.controlHorarioServicios = controlHorarioServicios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_control_servicio", unique=true, nullable=false)
    public Integer getIdControlServicio() {
        return this.idControlServicio;
    }
    
    public void setIdControlServicio(Integer idControlServicio) {
        this.idControlServicio = idControlServicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_control", nullable=false)
    public Control getControl() {
        return this.control;
    }
    
    public void setControl(Control control) {
        this.control = control;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_servicio", nullable=false)
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="tiempo", nullable=false, length=8)
    public Date getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(Date tiempo) {
        this.tiempo = tiempo;
    }

    
    @Column(name="numero_orden", nullable=false)
    public int getNumeroOrden() {
        return this.numeroOrden;
    }
    
    public void setNumeroOrden(int numeroOrden) {
        this.numeroOrden = numeroOrden;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="controlServicio")
    public Set<ControlHorarioServicio> getControlHorarioServicios() {
        return this.controlHorarioServicios;
    }
    
    public void setControlHorarioServicios(Set<ControlHorarioServicio> controlHorarioServicios) {
        this.controlHorarioServicios = controlHorarioServicios;
    }




}


