package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ControlAsistencia generated by hbm2java
 */
@Entity
@Table(name="control_asistencia"
    ,catalog="sigf_v1"
)
public class ControlAsistencia  implements java.io.Serializable {


     private Integer idControlAsistencia;
     private Trabajador trabajador;
     private Date horarioEntrada;
     private Date horarioSalida;

    public ControlAsistencia() {
    }

	
    public ControlAsistencia(Trabajador trabajador, Date horarioEntrada) {
        this.trabajador = trabajador;
        this.horarioEntrada = horarioEntrada;
    }
    public ControlAsistencia(Trabajador trabajador, Date horarioEntrada, Date horarioSalida) {
       this.trabajador = trabajador;
       this.horarioEntrada = horarioEntrada;
       this.horarioSalida = horarioSalida;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_control_asistencia", unique=true, nullable=false)
    public Integer getIdControlAsistencia() {
        return this.idControlAsistencia;
    }
    
    public void setIdControlAsistencia(Integer idControlAsistencia) {
        this.idControlAsistencia = idControlAsistencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_trabajador", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="horario_entrada", nullable=false, length=19)
    public Date getHorarioEntrada() {
        return this.horarioEntrada;
    }
    
    public void setHorarioEntrada(Date horarioEntrada) {
        this.horarioEntrada = horarioEntrada;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="horario_salida", length=19)
    public Date getHorarioSalida() {
        return this.horarioSalida;
    }
    
    public void setHorarioSalida(Date horarioSalida) {
        this.horarioSalida = horarioSalida;
    }




}


