package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CuentaBancariaTrabajador generated by hbm2java
 */
@Entity
@Table(name="cuenta_bancaria_trabajador"
    ,catalog="sigf_v1"
)
public class CuentaBancariaTrabajador  implements java.io.Serializable {


     private Integer idCuentaTrabajador;
     private Banco banco;
     private TipoCuentaBanco tipoCuentaBanco;
     private Trabajador trabajador;
     private String numeroCuenta;

    public CuentaBancariaTrabajador() {
    }

    public CuentaBancariaTrabajador(Banco banco, TipoCuentaBanco tipoCuentaBanco, Trabajador trabajador, String numeroCuenta) {
       this.banco = banco;
       this.tipoCuentaBanco = tipoCuentaBanco;
       this.trabajador = trabajador;
       this.numeroCuenta = numeroCuenta;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cuenta_trabajador", unique=true, nullable=false)
    public Integer getIdCuentaTrabajador() {
        return this.idCuentaTrabajador;
    }
    
    public void setIdCuentaTrabajador(Integer idCuentaTrabajador) {
        this.idCuentaTrabajador = idCuentaTrabajador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_banco", nullable=false)
    public Banco getBanco() {
        return this.banco;
    }
    
    public void setBanco(Banco banco) {
        this.banco = banco;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_cuenta", nullable=false)
    public TipoCuentaBanco getTipoCuentaBanco() {
        return this.tipoCuentaBanco;
    }
    
    public void setTipoCuentaBanco(TipoCuentaBanco tipoCuentaBanco) {
        this.tipoCuentaBanco = tipoCuentaBanco;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_trabajador", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    
    @Column(name="numero_cuenta", nullable=false, length=45)
    public String getNumeroCuenta() {
        return this.numeroCuenta;
    }
    
    public void setNumeroCuenta(String numeroCuenta) {
        this.numeroCuenta = numeroCuenta;
    }




}


