package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CuentaBancariaEmpresa generated by hbm2java
 */
@Entity
@Table(name="cuenta_bancaria_empresa"
    ,catalog="sigf_v1"
)
public class CuentaBancariaEmpresa  implements java.io.Serializable {


     private Integer idCuentaEmpresa;
     private Banco banco;
     private Empresa empresa;
     private TipoCuentaBanco tipoCuentaBanco;
     private String numeroCuentaEmpresa;

    public CuentaBancariaEmpresa() {
    }

    public CuentaBancariaEmpresa(Banco banco, Empresa empresa, TipoCuentaBanco tipoCuentaBanco, String numeroCuentaEmpresa) {
       this.banco = banco;
       this.empresa = empresa;
       this.tipoCuentaBanco = tipoCuentaBanco;
       this.numeroCuentaEmpresa = numeroCuentaEmpresa;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cuenta_empresa", unique=true, nullable=false)
    public Integer getIdCuentaEmpresa() {
        return this.idCuentaEmpresa;
    }
    
    public void setIdCuentaEmpresa(Integer idCuentaEmpresa) {
        this.idCuentaEmpresa = idCuentaEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_banco", nullable=false)
    public Banco getBanco() {
        return this.banco;
    }
    
    public void setBanco(Banco banco) {
        this.banco = banco;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_empresa", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_cuenta", nullable=false)
    public TipoCuentaBanco getTipoCuentaBanco() {
        return this.tipoCuentaBanco;
    }
    
    public void setTipoCuentaBanco(TipoCuentaBanco tipoCuentaBanco) {
        this.tipoCuentaBanco = tipoCuentaBanco;
    }

    
    @Column(name="numero_cuenta_empresa", nullable=false, length=45)
    public String getNumeroCuentaEmpresa() {
        return this.numeroCuentaEmpresa;
    }
    
    public void setNumeroCuentaEmpresa(String numeroCuentaEmpresa) {
        this.numeroCuentaEmpresa = numeroCuentaEmpresa;
    }




}


