package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DescuentoTrabajadorLiquidacion generated by hbm2java
 */
@Entity
@Table(name="descuento_trabajador_liquidacion"
    ,catalog="sigf_v1"
)
public class DescuentoTrabajadorLiquidacion  implements java.io.Serializable {


     private Integer idDescuentoTrabajadorLiquidacion;
     private DescuentoTrabajador descuentoTrabajador;
     private Trabajador trabajador;
     private Date fechaInicioDescuento;
     private Date fechaIngresoDescuento;
     private Integer numeroCuotas;
     private int monto;
     private boolean activoDescuentoTrabajador;
     private Set<DescuentoLiquidacion> descuentoLiquidacions = new HashSet<DescuentoLiquidacion>(0);

    public DescuentoTrabajadorLiquidacion() {
    }

	
    public DescuentoTrabajadorLiquidacion(DescuentoTrabajador descuentoTrabajador, Trabajador trabajador, Date fechaInicioDescuento, Date fechaIngresoDescuento, int monto, boolean activoDescuentoTrabajador) {
        this.descuentoTrabajador = descuentoTrabajador;
        this.trabajador = trabajador;
        this.fechaInicioDescuento = fechaInicioDescuento;
        this.fechaIngresoDescuento = fechaIngresoDescuento;
        this.monto = monto;
        this.activoDescuentoTrabajador = activoDescuentoTrabajador;
    }
    public DescuentoTrabajadorLiquidacion(DescuentoTrabajador descuentoTrabajador, Trabajador trabajador, Date fechaInicioDescuento, Date fechaIngresoDescuento, Integer numeroCuotas, int monto, boolean activoDescuentoTrabajador, Set<DescuentoLiquidacion> descuentoLiquidacions) {
       this.descuentoTrabajador = descuentoTrabajador;
       this.trabajador = trabajador;
       this.fechaInicioDescuento = fechaInicioDescuento;
       this.fechaIngresoDescuento = fechaIngresoDescuento;
       this.numeroCuotas = numeroCuotas;
       this.monto = monto;
       this.activoDescuentoTrabajador = activoDescuentoTrabajador;
       this.descuentoLiquidacions = descuentoLiquidacions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_descuento_trabajador_liquidacion", unique=true, nullable=false)
    public Integer getIdDescuentoTrabajadorLiquidacion() {
        return this.idDescuentoTrabajadorLiquidacion;
    }
    
    public void setIdDescuentoTrabajadorLiquidacion(Integer idDescuentoTrabajadorLiquidacion) {
        this.idDescuentoTrabajadorLiquidacion = idDescuentoTrabajadorLiquidacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_descuento_trabajador", nullable=false)
    public DescuentoTrabajador getDescuentoTrabajador() {
        return this.descuentoTrabajador;
    }
    
    public void setDescuentoTrabajador(DescuentoTrabajador descuentoTrabajador) {
        this.descuentoTrabajador = descuentoTrabajador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_trabajador", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio_descuento", nullable=false, length=10)
    public Date getFechaInicioDescuento() {
        return this.fechaInicioDescuento;
    }
    
    public void setFechaInicioDescuento(Date fechaInicioDescuento) {
        this.fechaInicioDescuento = fechaInicioDescuento;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_ingreso_descuento", nullable=false, length=19)
    public Date getFechaIngresoDescuento() {
        return this.fechaIngresoDescuento;
    }
    
    public void setFechaIngresoDescuento(Date fechaIngresoDescuento) {
        this.fechaIngresoDescuento = fechaIngresoDescuento;
    }

    
    @Column(name="numero_cuotas")
    public Integer getNumeroCuotas() {
        return this.numeroCuotas;
    }
    
    public void setNumeroCuotas(Integer numeroCuotas) {
        this.numeroCuotas = numeroCuotas;
    }

    
    @Column(name="monto", nullable=false)
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }

    
    @Column(name="activo_descuento_trabajador", nullable=false)
    public boolean isActivoDescuentoTrabajador() {
        return this.activoDescuentoTrabajador;
    }
    
    public void setActivoDescuentoTrabajador(boolean activoDescuentoTrabajador) {
        this.activoDescuentoTrabajador = activoDescuentoTrabajador;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="descuentoTrabajadorLiquidacion")
    public Set<DescuentoLiquidacion> getDescuentoLiquidacions() {
        return this.descuentoLiquidacions;
    }
    
    public void setDescuentoLiquidacions(Set<DescuentoLiquidacion> descuentoLiquidacions) {
        this.descuentoLiquidacions = descuentoLiquidacions;
    }




}


