package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DescuentoLiquidacion generated by hbm2java
 */
@Entity
@Table(name="descuento_liquidacion"
    ,catalog="sigf_v1"
)
public class DescuentoLiquidacion  implements java.io.Serializable {


     private int idDescuentoLiquidacion;
     private DescuentoTrabajadorLiquidacion descuentoTrabajadorLiquidacion;
     private LiquidacionSueldo liquidacionSueldo;
     private int montoDescuento;

    public DescuentoLiquidacion() {
    }

    public DescuentoLiquidacion(int idDescuentoLiquidacion, DescuentoTrabajadorLiquidacion descuentoTrabajadorLiquidacion, LiquidacionSueldo liquidacionSueldo, int montoDescuento) {
       this.idDescuentoLiquidacion = idDescuentoLiquidacion;
       this.descuentoTrabajadorLiquidacion = descuentoTrabajadorLiquidacion;
       this.liquidacionSueldo = liquidacionSueldo;
       this.montoDescuento = montoDescuento;
    }
   
     @Id 

    
    @Column(name="id_descuento_liquidacion", unique=true, nullable=false)
    public int getIdDescuentoLiquidacion() {
        return this.idDescuentoLiquidacion;
    }
    
    public void setIdDescuentoLiquidacion(int idDescuentoLiquidacion) {
        this.idDescuentoLiquidacion = idDescuentoLiquidacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_descuento_trabajador_liquidacion", nullable=false)
    public DescuentoTrabajadorLiquidacion getDescuentoTrabajadorLiquidacion() {
        return this.descuentoTrabajadorLiquidacion;
    }
    
    public void setDescuentoTrabajadorLiquidacion(DescuentoTrabajadorLiquidacion descuentoTrabajadorLiquidacion) {
        this.descuentoTrabajadorLiquidacion = descuentoTrabajadorLiquidacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_liquidacion_sueldo", nullable=false)
    public LiquidacionSueldo getLiquidacionSueldo() {
        return this.liquidacionSueldo;
    }
    
    public void setLiquidacionSueldo(LiquidacionSueldo liquidacionSueldo) {
        this.liquidacionSueldo = liquidacionSueldo;
    }

    
    @Column(name="monto_descuento", nullable=false)
    public int getMontoDescuento() {
        return this.montoDescuento;
    }
    
    public void setMontoDescuento(int montoDescuento) {
        this.montoDescuento = montoDescuento;
    }




}


