package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Despacho generated by hbm2java
 */
@Entity
@Table(name="despacho"
    ,catalog="sigf_v1"
)
public class Despacho  implements java.io.Serializable {


     private Integer idDespacho;
     private Bus bus;
     private Servicio servicio;
     private Trabajador trabajador;
     private Usuario usuario;
     private Date fecha;
     private Date horario;

    public Despacho() {
    }

    public Despacho(Bus bus, Servicio servicio, Trabajador trabajador, Usuario usuario, Date fecha, Date horario) {
       this.bus = bus;
       this.servicio = servicio;
       this.trabajador = trabajador;
       this.usuario = usuario;
       this.fecha = fecha;
       this.horario = horario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_despacho", unique=true, nullable=false)
    public Integer getIdDespacho() {
        return this.idDespacho;
    }
    
    public void setIdDespacho(Integer idDespacho) {
        this.idDespacho = idDespacho;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_bus", nullable=false)
    public Bus getBus() {
        return this.bus;
    }
    
    public void setBus(Bus bus) {
        this.bus = bus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_servicio", nullable=false)
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_trabajador", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_inspector", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="horario", nullable=false, length=8)
    public Date getHorario() {
        return this.horario;
    }
    
    public void setHorario(Date horario) {
        this.horario = horario;
    }




}


