package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleIntervalosMensual generated by hbm2java
 */
@Entity
@Table(name="detalle_intervalos_mensual"
    ,catalog="sigf_v1"
)
public class DetalleIntervalosMensual  implements java.io.Serializable {


     private Integer idDetalleIntervalosMensual;
     private AdministracionMensual administracionMensual;
     private IntervalosAdministracion intervalosAdministracion;
     private int numeroBuses;

    public DetalleIntervalosMensual() {
    }

    public DetalleIntervalosMensual(AdministracionMensual administracionMensual, IntervalosAdministracion intervalosAdministracion, int numeroBuses) {
       this.administracionMensual = administracionMensual;
       this.intervalosAdministracion = intervalosAdministracion;
       this.numeroBuses = numeroBuses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_detalle_intervalos_mensual", unique=true, nullable=false)
    public Integer getIdDetalleIntervalosMensual() {
        return this.idDetalleIntervalosMensual;
    }
    
    public void setIdDetalleIntervalosMensual(Integer idDetalleIntervalosMensual) {
        this.idDetalleIntervalosMensual = idDetalleIntervalosMensual;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_administracion_mensual", nullable=false)
    public AdministracionMensual getAdministracionMensual() {
        return this.administracionMensual;
    }
    
    public void setAdministracionMensual(AdministracionMensual administracionMensual) {
        this.administracionMensual = administracionMensual;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_intervalo_administracion", nullable=false)
    public IntervalosAdministracion getIntervalosAdministracion() {
        return this.intervalosAdministracion;
    }
    
    public void setIntervalosAdministracion(IntervalosAdministracion intervalosAdministracion) {
        this.intervalosAdministracion = intervalosAdministracion;
    }

    
    @Column(name="numero_buses", nullable=false)
    public int getNumeroBuses() {
        return this.numeroBuses;
    }
    
    public void setNumeroBuses(int numeroBuses) {
        this.numeroBuses = numeroBuses;
    }




}


