package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleCompraBoleto generated by hbm2java
 */
@Entity
@Table(name = "detalle_compra_boleto", catalog = "sigf_v1"
)
public class DetalleCompraBoleto implements java.io.Serializable {

    private Integer idDetalleCompraBoleto;
    private Boleto boleto;
    private CompraBoleto compraBoleto;
    private int cantidadRollos;
    private String identificador;
    private String serie;
    private int total;

    public DetalleCompraBoleto() {
    }

    public DetalleCompraBoleto(Boleto boleto, CompraBoleto compraBoleto, int cantidadRollos, int total) {
        this.boleto = boleto;
        this.compraBoleto = compraBoleto;
        this.cantidadRollos = cantidadRollos;
        this.total = total;
    }

    public DetalleCompraBoleto(Boleto boleto, CompraBoleto compraBoleto, int cantidadRollos, String serie, String identificador, int total) {
        this.boleto = boleto;
        this.compraBoleto = compraBoleto;
        this.cantidadRollos = cantidadRollos;
        this.identificador = identificador;
        this.serie = serie;
        this.total = total;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_detalle_compra_boleto", unique = true, nullable = false)
    public Integer getIdDetalleCompraBoleto() {
        return this.idDetalleCompraBoleto;
    }

    public void setIdDetalleCompraBoleto(Integer idDetalleCompraBoleto) {
        this.idDetalleCompraBoleto = idDetalleCompraBoleto;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_boleto", nullable = false)
    public Boleto getBoleto() {
        return this.boleto;
    }

    public void setBoleto(Boleto boleto) {
        this.boleto = boleto;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_compra_boleto", nullable = false)
    public CompraBoleto getCompraBoleto() {
        return this.compraBoleto;
    }

    public void setCompraBoleto(CompraBoleto compraBoleto) {
        this.compraBoleto = compraBoleto;
    }

    @Column(name = "cantidad_rollos", nullable = false)
    public int getCantidadRollos() {
        return this.cantidadRollos;
    }

    public void setCantidadRollos(int cantidadRollos) {
        this.cantidadRollos = cantidadRollos;
    }

    @Column(name = "identificador", length = 45, nullable = false)
    public String getIdentificador() {
        return this.identificador;
    }

    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }

    @Column(name = "serie", length = 45, nullable = false)
    public String getSerie() {
        return this.serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    @Column(name = "total", nullable = false)
    public int getTotal() {
        return this.total;
    }

    public void setTotal(int total) {
        this.total = total;
    }

}
