package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Device generated by hbm2java
 */
@Entity
@Table(name="device"
    ,catalog="sigf_v1"
    , uniqueConstraints = @UniqueConstraint(columnNames="uniqueId") 
)
public class Device  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String uniqueId;
     private String status;
     private Date lastUpdate;
     private Integer positionId;
     private Set<Position> positions = new HashSet<Position>(0);
     private Set<BusDevice> busDevices = new HashSet<BusDevice>(0);
     private Set<UserDevice> userDevices = new HashSet<UserDevice>(0);

    public Device() {
    }

	
    public Device(String name, String uniqueId, Date lastUpdate) {
        this.name = name;
        this.uniqueId = uniqueId;
        this.lastUpdate = lastUpdate;
    }
    public Device(String name, String uniqueId, String status, Date lastUpdate, Integer positionId, Set<Position> positions, Set<BusDevice> busDevices, Set<UserDevice> userDevices) {
       this.name = name;
       this.uniqueId = uniqueId;
       this.status = status;
       this.lastUpdate = lastUpdate;
       this.positionId = positionId;
       this.positions = positions;
       this.busDevices = busDevices;
       this.userDevices = userDevices;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=128)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="uniqueId", unique=true, nullable=false, length=128)
    public String getUniqueId() {
        return this.uniqueId;
    }
    
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    
    @Column(name="status", length=128)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastUpdate", nullable=false, length=19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    
    @Column(name="positionId")
    public Integer getPositionId() {
        return this.positionId;
    }
    
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="device")
    public Set<Position> getPositions() {
        return this.positions;
    }
    
    public void setPositions(Set<Position> positions) {
        this.positions = positions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="device")
    public Set<BusDevice> getBusDevices() {
        return this.busDevices;
    }
    
    public void setBusDevices(Set<BusDevice> busDevices) {
        this.busDevices = busDevices;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="device")
    public Set<UserDevice> getUserDevices() {
        return this.userDevices;
    }
    
    public void setUserDevices(Set<UserDevice> userDevices) {
        this.userDevices = userDevices;
    }




}


