package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Egreso generated by hbm2java
 */
@Entity
@Table(name = "egreso", catalog = "sigf_v1"
)
public class Egreso implements java.io.Serializable {

    private Integer idEgreso;
    private String nombreEgreso;
    private boolean activo;
    private Set<EgresoRecaudacion> egresoRecaudacions = new HashSet<EgresoRecaudacion>(0);

    public Egreso() {
    }

    public Egreso(String nombreEgreso, boolean activo) {
        this.nombreEgreso = nombreEgreso;
        this.activo = activo;
    }

    public Egreso(String nombreEgreso, boolean activo, Set<EgresoRecaudacion> egresoRecaudacions) {
        this.nombreEgreso = nombreEgreso;
        this.activo = activo;
        this.egresoRecaudacions = egresoRecaudacions;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_egreso", unique = true, nullable = false)
    public Integer getIdEgreso() {
        return this.idEgreso;
    }

    public void setIdEgreso(Integer idEgreso) {
        this.idEgreso = idEgreso;
    }

    @Column(name = "nombre_egreso", nullable = false, length = 45)
    public String getNombreEgreso() {
        return this.nombreEgreso;
    }

    public void setNombreEgreso(String nombreEgreso) {
        this.nombreEgreso = nombreEgreso;
    }

    @Column(name = "activo", nullable = false)
    public boolean isActivo() {
        return this.activo;
    }

    public void setActivo(boolean activo) {
        this.activo = activo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "egreso")
    public Set<EgresoRecaudacion> getEgresoRecaudacions() {
        return this.egresoRecaudacions;
    }

    public void setEgresoRecaudacions(Set<EgresoRecaudacion> egresoRecaudacions) {
        this.egresoRecaudacions = egresoRecaudacions;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idEgreso != null ? idEgreso.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Egreso)) {
            return false;
        }
        Egreso other = (Egreso) object;
        if ((this.idEgreso == null && other.idEgreso != null) || (this.idEgreso != null && !this.idEgreso.equals(other.idEgreso))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return nombreEgreso;
    }

}
