package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EgresoRecaudacion generated by hbm2java
 */
@Entity
@Table(name="egreso_recaudacion"
    ,catalog="sigf_v1"
)
public class EgresoRecaudacion  implements java.io.Serializable {


     private int idEgresoRecaudacion;
     private Egreso egreso;
     private ProcesoRecaudacion procesoRecaudacion;
     private int valorDefectoEgreso;
     private BigDecimal porcentaje;
     private int numeroOrdenEgreso;
     private boolean activo;
     private Set<EgresoGuia> egresoGuias = new HashSet<EgresoGuia>(0);

    public EgresoRecaudacion() {
    }

	
    public EgresoRecaudacion(int idEgresoRecaudacion, Egreso egreso, ProcesoRecaudacion procesoRecaudacion, int valorDefectoEgreso, BigDecimal porcentaje, int numeroOrdenEgreso, boolean activo) {
        this.idEgresoRecaudacion = idEgresoRecaudacion;
        this.egreso = egreso;
        this.procesoRecaudacion = procesoRecaudacion;
        this.valorDefectoEgreso = valorDefectoEgreso;
        this.porcentaje = porcentaje;
        this.numeroOrdenEgreso = numeroOrdenEgreso;
        this.activo = activo;
    }
    public EgresoRecaudacion(int idEgresoRecaudacion, Egreso egreso, ProcesoRecaudacion procesoRecaudacion, int valorDefectoEgreso, BigDecimal porcentaje, int numeroOrdenEgreso, boolean activo, Set<EgresoGuia> egresoGuias) {
       this.idEgresoRecaudacion = idEgresoRecaudacion;
       this.egreso = egreso;
       this.procesoRecaudacion = procesoRecaudacion;
       this.valorDefectoEgreso = valorDefectoEgreso;
       this.porcentaje = porcentaje;
       this.numeroOrdenEgreso = numeroOrdenEgreso;
       this.activo = activo;
       this.egresoGuias = egresoGuias;
    }
   
     @Id 

    
    @Column(name="id_egreso_recaudacion", unique=true, nullable=false)
    public int getIdEgresoRecaudacion() {
        return this.idEgresoRecaudacion;
    }
    
    public void setIdEgresoRecaudacion(int idEgresoRecaudacion) {
        this.idEgresoRecaudacion = idEgresoRecaudacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_egreso", nullable=false)
    public Egreso getEgreso() {
        return this.egreso;
    }
    
    public void setEgreso(Egreso egreso) {
        this.egreso = egreso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_proceso_recaudacion", nullable=false)
    public ProcesoRecaudacion getProcesoRecaudacion() {
        return this.procesoRecaudacion;
    }
    
    public void setProcesoRecaudacion(ProcesoRecaudacion procesoRecaudacion) {
        this.procesoRecaudacion = procesoRecaudacion;
    }

    
    @Column(name="valor_defecto_egreso", nullable=false)
    public int getValorDefectoEgreso() {
        return this.valorDefectoEgreso;
    }
    
    public void setValorDefectoEgreso(int valorDefectoEgreso) {
        this.valorDefectoEgreso = valorDefectoEgreso;
    }

    
    @Column(name="porcentaje", nullable=false, precision=10)
    public BigDecimal getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(BigDecimal porcentaje) {
        this.porcentaje = porcentaje;
    }

    
    @Column(name="numero_orden_egreso", nullable=false)
    public int getNumeroOrdenEgreso() {
        return this.numeroOrdenEgreso;
    }
    
    public void setNumeroOrdenEgreso(int numeroOrdenEgreso) {
        this.numeroOrdenEgreso = numeroOrdenEgreso;
    }

    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="egresoRecaudacion")
    public Set<EgresoGuia> getEgresoGuias() {
        return this.egresoGuias;
    }
    
    public void setEgresoGuias(Set<EgresoGuia> egresoGuias) {
        this.egresoGuias = egresoGuias;
    }




}


