package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EgresoGuia generated by hbm2java
 */
@Entity
@Table(name="egreso_guia"
    ,catalog="sigf_v1"
)
public class EgresoGuia  implements java.io.Serializable {


     private Integer idEgresoGuia;
     private EgresoRecaudacion egresoRecaudacion;
     private Guia guia;
     private int monto;

    public EgresoGuia() {
    }

    public EgresoGuia(EgresoRecaudacion egresoRecaudacion, Guia guia, int monto) {
       this.egresoRecaudacion = egresoRecaudacion;
       this.guia = guia;
       this.monto = monto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_egreso_guia", unique=true, nullable=false)
    public Integer getIdEgresoGuia() {
        return this.idEgresoGuia;
    }
    
    public void setIdEgresoGuia(Integer idEgresoGuia) {
        this.idEgresoGuia = idEgresoGuia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_egreso_servicio", nullable=false)
    public EgresoRecaudacion getEgresoRecaudacion() {
        return this.egresoRecaudacion;
    }
    
    public void setEgresoRecaudacion(EgresoRecaudacion egresoRecaudacion) {
        this.egresoRecaudacion = egresoRecaudacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_guia", nullable=false)
    public Guia getGuia() {
        return this.guia;
    }
    
    public void setGuia(Guia guia) {
        this.guia = guia;
    }

    
    @Column(name="monto", nullable=false)
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }




}


