package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoBus generated by hbm2java
 */
@Entity
@Table(name = "estado_bus", catalog = "sigf_v1"
)
public class EstadoBus implements java.io.Serializable {

    private int idEstadoBus;
    private String nombreEstadoBus;
    private Set<Bus> buses = new HashSet<Bus>(0);

    public EstadoBus() {
    }

    public EstadoBus(int idEstadoBus, String nombreEstadoBus) {
        this.idEstadoBus = idEstadoBus;
        this.nombreEstadoBus = nombreEstadoBus;
    }

    public EstadoBus(int idEstadoBus, String nombreEstadoBus, Set<Bus> buses) {
        this.idEstadoBus = idEstadoBus;
        this.nombreEstadoBus = nombreEstadoBus;
        this.buses = buses;
    }

    @Id

    @Column(name = "id_estado_bus", unique = true, nullable = false)
    public int getIdEstadoBus() {
        return this.idEstadoBus;
    }

    public void setIdEstadoBus(int idEstadoBus) {
        this.idEstadoBus = idEstadoBus;
    }

    @Column(name = "nombre_estado_bus", nullable = false, length = 100)
    public String getNombreEstadoBus() {
        return this.nombreEstadoBus;
    }

    public void setNombreEstadoBus(String nombreEstadoBus) {
        this.nombreEstadoBus = nombreEstadoBus;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoBus")
    public Set<Bus> getBuses() {
        return this.buses;
    }

    public void setBuses(Set<Bus> buses) {
        this.buses = buses;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 43 * hash + this.idEstadoBus;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EstadoBus other = (EstadoBus) obj;
        if (this.idEstadoBus != other.idEstadoBus) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return nombreEstadoBus;
    }

}
