package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoGuia generated by hbm2java
 */
@Entity
@Table(name="estado_guia"
    ,catalog="sigf_v1"
)
public class EstadoGuia  implements java.io.Serializable {


     private int idEstadoGuia;
     private String nombreEstado;
     private boolean activo;
     private Set<Guia> guias = new HashSet<Guia>(0);

    public EstadoGuia() {
    }

	
    public EstadoGuia(int idEstadoGuia, String nombreEstado, boolean activo) {
        this.idEstadoGuia = idEstadoGuia;
        this.nombreEstado = nombreEstado;
        this.activo = activo;
    }
    public EstadoGuia(int idEstadoGuia, String nombreEstado, boolean activo, Set<Guia> guias) {
       this.idEstadoGuia = idEstadoGuia;
       this.nombreEstado = nombreEstado;
       this.activo = activo;
       this.guias = guias;
    }
   
     @Id 

    
    @Column(name="id_estado_guia", unique=true, nullable=false)
    public int getIdEstadoGuia() {
        return this.idEstadoGuia;
    }
    
    public void setIdEstadoGuia(int idEstadoGuia) {
        this.idEstadoGuia = idEstadoGuia;
    }

    
    @Column(name="nombre_estado", nullable=false, length=45)
    public String getNombreEstado() {
        return this.nombreEstado;
    }
    
    public void setNombreEstado(String nombreEstado) {
        this.nombreEstado = nombreEstado;
    }

    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estadoGuia")
    public Set<Guia> getGuias() {
        return this.guias;
    }
    
    public void setGuias(Set<Guia> guias) {
        this.guias = guias;
    }




}


