package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FeriadoLegal generated by hbm2java
 */
@Entity
@Table(name="feriado_legal"
    ,catalog="sigf_v1"
)
public class FeriadoLegal  implements java.io.Serializable {


     private Integer idFeriadoLegal;
     private Trabajador trabajador;
     private Date fechaIngresoFeriado;
     private Date fechaDesdeFeriado;
     private Date fechaHastaFeriado;
     private Integer diasHabiles;
     private Integer vacacionesProgresivas;
     private Integer domingosInhabiles;
     private Integer feriadoFraccionado;
     private Integer saldoPendiente;
     private Integer valorFeriado;

    public FeriadoLegal() {
    }

	
    public FeriadoLegal(Trabajador trabajador, Date fechaIngresoFeriado, Date fechaDesdeFeriado, Date fechaHastaFeriado) {
        this.trabajador = trabajador;
        this.fechaIngresoFeriado = fechaIngresoFeriado;
        this.fechaDesdeFeriado = fechaDesdeFeriado;
        this.fechaHastaFeriado = fechaHastaFeriado;
    }
    public FeriadoLegal(Trabajador trabajador, Date fechaIngresoFeriado, Date fechaDesdeFeriado, Date fechaHastaFeriado, Integer diasHabiles, Integer vacacionesProgresivas, Integer domingosInhabiles, Integer feriadoFraccionado, Integer saldoPendiente, Integer valorFeriado) {
       this.trabajador = trabajador;
       this.fechaIngresoFeriado = fechaIngresoFeriado;
       this.fechaDesdeFeriado = fechaDesdeFeriado;
       this.fechaHastaFeriado = fechaHastaFeriado;
       this.diasHabiles = diasHabiles;
       this.vacacionesProgresivas = vacacionesProgresivas;
       this.domingosInhabiles = domingosInhabiles;
       this.feriadoFraccionado = feriadoFraccionado;
       this.saldoPendiente = saldoPendiente;
       this.valorFeriado = valorFeriado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_feriado_legal", unique=true, nullable=false)
    public Integer getIdFeriadoLegal() {
        return this.idFeriadoLegal;
    }
    
    public void setIdFeriadoLegal(Integer idFeriadoLegal) {
        this.idFeriadoLegal = idFeriadoLegal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_trabajador", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_ingreso_feriado", nullable=false, length=19)
    public Date getFechaIngresoFeriado() {
        return this.fechaIngresoFeriado;
    }
    
    public void setFechaIngresoFeriado(Date fechaIngresoFeriado) {
        this.fechaIngresoFeriado = fechaIngresoFeriado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_desde_feriado", nullable=false, length=10)
    public Date getFechaDesdeFeriado() {
        return this.fechaDesdeFeriado;
    }
    
    public void setFechaDesdeFeriado(Date fechaDesdeFeriado) {
        this.fechaDesdeFeriado = fechaDesdeFeriado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_hasta_feriado", nullable=false, length=10)
    public Date getFechaHastaFeriado() {
        return this.fechaHastaFeriado;
    }
    
    public void setFechaHastaFeriado(Date fechaHastaFeriado) {
        this.fechaHastaFeriado = fechaHastaFeriado;
    }

    
    @Column(name="dias_habiles")
    public Integer getDiasHabiles() {
        return this.diasHabiles;
    }
    
    public void setDiasHabiles(Integer diasHabiles) {
        this.diasHabiles = diasHabiles;
    }

    
    @Column(name="vacaciones_progresivas")
    public Integer getVacacionesProgresivas() {
        return this.vacacionesProgresivas;
    }
    
    public void setVacacionesProgresivas(Integer vacacionesProgresivas) {
        this.vacacionesProgresivas = vacacionesProgresivas;
    }

    
    @Column(name="domingos_inhabiles")
    public Integer getDomingosInhabiles() {
        return this.domingosInhabiles;
    }
    
    public void setDomingosInhabiles(Integer domingosInhabiles) {
        this.domingosInhabiles = domingosInhabiles;
    }

    
    @Column(name="feriado_fraccionado")
    public Integer getFeriadoFraccionado() {
        return this.feriadoFraccionado;
    }
    
    public void setFeriadoFraccionado(Integer feriadoFraccionado) {
        this.feriadoFraccionado = feriadoFraccionado;
    }

    
    @Column(name="saldo_pendiente")
    public Integer getSaldoPendiente() {
        return this.saldoPendiente;
    }
    
    public void setSaldoPendiente(Integer saldoPendiente) {
        this.saldoPendiente = saldoPendiente;
    }

    
    @Column(name="valor_feriado")
    public Integer getValorFeriado() {
        return this.valorFeriado;
    }
    
    public void setValorFeriado(Integer valorFeriado) {
        this.valorFeriado = valorFeriado;
    }

    @Override
    public String toString() {
        Calendar calendarDesde = GregorianCalendar.getInstance();
        calendarDesde.setTime(fechaDesdeFeriado);
        
        Calendar calendarHasta = GregorianCalendar.getInstance();
        calendarHasta.setTime(fechaHastaFeriado);
        
        int dias = (calendarHasta.get(Calendar.DATE)-calendarDesde.get(Calendar.DATE))+1;
        
        return String.valueOf(dias);
    }

}


