package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FiniquitoRelacionLaboral generated by hbm2java
 */
@Entity
@Table(name="finiquito_relacion_laboral"
    ,catalog="sigf_v1"
)
public class FiniquitoRelacionLaboral  implements java.io.Serializable {


     private int idFiniquitoRelacionLaboral;
     private CausalFiniquito causalFiniquito;
     private RelacionLaboral relacionLaboral;
     private Date fechaFiniquito;
     private Date fechaRegistroFiniquito;
     private int montoFiniquito;
     private Integer aniosServicio;
     private Integer aniosAdicionales;

    public FiniquitoRelacionLaboral() {
    }

	
    public FiniquitoRelacionLaboral(int idFiniquitoRelacionLaboral, CausalFiniquito causalFiniquito, RelacionLaboral relacionLaboral, Date fechaFiniquito, int montoFiniquito) {
        this.idFiniquitoRelacionLaboral = idFiniquitoRelacionLaboral;
        this.causalFiniquito = causalFiniquito;
        this.relacionLaboral = relacionLaboral;
        this.fechaFiniquito = fechaFiniquito;
        this.montoFiniquito = montoFiniquito;
    }
    public FiniquitoRelacionLaboral(int idFiniquitoRelacionLaboral, CausalFiniquito causalFiniquito, RelacionLaboral relacionLaboral, Date fechaFiniquito, Date fechaRegistroFiniquito, int montoFiniquito, Integer aniosServicio, Integer aniosAdicionales) {
       this.idFiniquitoRelacionLaboral = idFiniquitoRelacionLaboral;
       this.causalFiniquito = causalFiniquito;
       this.relacionLaboral = relacionLaboral;
       this.fechaFiniquito = fechaFiniquito;
       this.fechaRegistroFiniquito = fechaRegistroFiniquito;
       this.montoFiniquito = montoFiniquito;
       this.aniosServicio = aniosServicio;
       this.aniosAdicionales = aniosAdicionales;
    }
   
     @Id 

    
    @Column(name="id_finiquito_relacion_laboral", unique=true, nullable=false)
    public int getIdFiniquitoRelacionLaboral() {
        return this.idFiniquitoRelacionLaboral;
    }
    
    public void setIdFiniquitoRelacionLaboral(int idFiniquitoRelacionLaboral) {
        this.idFiniquitoRelacionLaboral = idFiniquitoRelacionLaboral;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_causal_finiquito", nullable=false)
    public CausalFiniquito getCausalFiniquito() {
        return this.causalFiniquito;
    }
    
    public void setCausalFiniquito(CausalFiniquito causalFiniquito) {
        this.causalFiniquito = causalFiniquito;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_relacion_laboral", nullable=false)
    public RelacionLaboral getRelacionLaboral() {
        return this.relacionLaboral;
    }
    
    public void setRelacionLaboral(RelacionLaboral relacionLaboral) {
        this.relacionLaboral = relacionLaboral;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_finiquito", nullable=false, length=10)
    public Date getFechaFiniquito() {
        return this.fechaFiniquito;
    }
    
    public void setFechaFiniquito(Date fechaFiniquito) {
        this.fechaFiniquito = fechaFiniquito;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_registro_finiquito", length=19)
    public Date getFechaRegistroFiniquito() {
        return this.fechaRegistroFiniquito;
    }
    
    public void setFechaRegistroFiniquito(Date fechaRegistroFiniquito) {
        this.fechaRegistroFiniquito = fechaRegistroFiniquito;
    }

    
    @Column(name="monto_finiquito", nullable=false)
    public int getMontoFiniquito() {
        return this.montoFiniquito;
    }
    
    public void setMontoFiniquito(int montoFiniquito) {
        this.montoFiniquito = montoFiniquito;
    }

    
    @Column(name="anios_servicio")
    public Integer getAniosServicio() {
        return this.aniosServicio;
    }
    
    public void setAniosServicio(Integer aniosServicio) {
        this.aniosServicio = aniosServicio;
    }

    
    @Column(name="anios_adicionales")
    public Integer getAniosAdicionales() {
        return this.aniosAdicionales;
    }
    
    public void setAniosAdicionales(Integer aniosAdicionales) {
        this.aniosAdicionales = aniosAdicionales;
    }




}


