package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Flota generated by hbm2java
 */
@Entity
@Table(name="flota"
    ,catalog="sigf_v1"
)
public class Flota  implements java.io.Serializable {


     private Integer idFlota;
     private String nombreFlota;
     private Set<Bus> buses = new HashSet<Bus>(0);

    public Flota() {
    }

	
    public Flota(String nombreFlota) {
        this.nombreFlota = nombreFlota;
    }
    public Flota(String nombreFlota, Set<Bus> buses) {
       this.nombreFlota = nombreFlota;
       this.buses = buses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_flota", unique=true, nullable=false)
    public Integer getIdFlota() {
        return this.idFlota;
    }
    
    public void setIdFlota(Integer idFlota) {
        this.idFlota = idFlota;
    }

    
    @Column(name="nombre_flota", nullable=false, length=45)
    public String getNombreFlota() {
        return this.nombreFlota;
    }
    
    public void setNombreFlota(String nombreFlota) {
        this.nombreFlota = nombreFlota;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="flota")
    public Set<Bus> getBuses() {
        return this.buses;
    }
    
    public void setBuses(Set<Bus> buses) {
        this.buses = buses;
    }




}


