package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FormaPago generated by hbm2java
 */
@Entity
@Table(name="forma_pago"
    ,catalog="sigf_v1"
)
public class FormaPago  implements java.io.Serializable {


     private Integer idFormaPago;
     private String nombreFormaPago;
     private Set<FormaPagoTrabajador> formaPagoTrabajadors = new HashSet<FormaPagoTrabajador>(0);

    public FormaPago() {
    }

	
    public FormaPago(String nombreFormaPago) {
        this.nombreFormaPago = nombreFormaPago;
    }
    public FormaPago(String nombreFormaPago, Set<FormaPagoTrabajador> formaPagoTrabajadors) {
       this.nombreFormaPago = nombreFormaPago;
       this.formaPagoTrabajadors = formaPagoTrabajadors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_forma_pago", unique=true, nullable=false)
    public Integer getIdFormaPago() {
        return this.idFormaPago;
    }
    
    public void setIdFormaPago(Integer idFormaPago) {
        this.idFormaPago = idFormaPago;
    }

    
    @Column(name="nombre_forma_pago", nullable=false, length=45)
    public String getNombreFormaPago() {
        return this.nombreFormaPago;
    }
    
    public void setNombreFormaPago(String nombreFormaPago) {
        this.nombreFormaPago = nombreFormaPago;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="formaPago")
    public Set<FormaPagoTrabajador> getFormaPagoTrabajadors() {
        return this.formaPagoTrabajadors;
    }
    
    public void setFormaPagoTrabajadors(Set<FormaPagoTrabajador> formaPagoTrabajadors) {
        this.formaPagoTrabajadors = formaPagoTrabajadors;
    }




}


