package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GastosAdministracionMensual generated by hbm2java
 */
@Entity
@Table(name="gastos_administracion_mensual"
    ,catalog="sigf_v1"
)
public class GastosAdministracionMensual  implements java.io.Serializable {


     private Integer idGastosAdministracionMensual;
     private Departamento departamento;
     private int mes;
     private int anio;
     private int numeroFolio;
     private String nombreGastoAdministracion;
     private Date fechaGastoAdministracion;
     private Date fechaIngreso;
     private Date valor;
     private String observacion;

    public GastosAdministracionMensual() {
    }

	
    public GastosAdministracionMensual(Departamento departamento, int mes, int anio, int numeroFolio, String nombreGastoAdministracion, Date fechaGastoAdministracion, Date fechaIngreso, Date valor) {
        this.departamento = departamento;
        this.mes = mes;
        this.anio = anio;
        this.numeroFolio = numeroFolio;
        this.nombreGastoAdministracion = nombreGastoAdministracion;
        this.fechaGastoAdministracion = fechaGastoAdministracion;
        this.fechaIngreso = fechaIngreso;
        this.valor = valor;
    }
    public GastosAdministracionMensual(Departamento departamento, int mes, int anio, int numeroFolio, String nombreGastoAdministracion, Date fechaGastoAdministracion, Date fechaIngreso, Date valor, String observacion) {
       this.departamento = departamento;
       this.mes = mes;
       this.anio = anio;
       this.numeroFolio = numeroFolio;
       this.nombreGastoAdministracion = nombreGastoAdministracion;
       this.fechaGastoAdministracion = fechaGastoAdministracion;
       this.fechaIngreso = fechaIngreso;
       this.valor = valor;
       this.observacion = observacion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_gastos_administracion_mensual", unique=true, nullable=false)
    public Integer getIdGastosAdministracionMensual() {
        return this.idGastosAdministracionMensual;
    }
    
    public void setIdGastosAdministracionMensual(Integer idGastosAdministracionMensual) {
        this.idGastosAdministracionMensual = idGastosAdministracionMensual;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_departamento", nullable=false)
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="mes", nullable=false)
    public int getMes() {
        return this.mes;
    }
    
    public void setMes(int mes) {
        this.mes = mes;
    }

    
    @Column(name="anio", nullable=false)
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }

    
    @Column(name="numero_folio", nullable=false)
    public int getNumeroFolio() {
        return this.numeroFolio;
    }
    
    public void setNumeroFolio(int numeroFolio) {
        this.numeroFolio = numeroFolio;
    }

    
    @Column(name="nombre_gasto_administracion", nullable=false, length=45)
    public String getNombreGastoAdministracion() {
        return this.nombreGastoAdministracion;
    }
    
    public void setNombreGastoAdministracion(String nombreGastoAdministracion) {
        this.nombreGastoAdministracion = nombreGastoAdministracion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_gasto_administracion", nullable=false, length=10)
    public Date getFechaGastoAdministracion() {
        return this.fechaGastoAdministracion;
    }
    
    public void setFechaGastoAdministracion(Date fechaGastoAdministracion) {
        this.fechaGastoAdministracion = fechaGastoAdministracion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_ingreso", nullable=false, length=10)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="valor", nullable=false, length=10)
    public Date getValor() {
        return this.valor;
    }
    
    public void setValor(Date valor) {
        this.valor = valor;
    }

    
    @Column(name="observacion")
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


