package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GastoAdministracionMensual generated by hbm2java
 */
@Entity
@Table(name = "gasto_administracion_mensual", catalog = "sigf_v1"
)
public class GastoAdministracionMensual implements java.io.Serializable {

    private Integer idGastoAdministracionMensual;
    private Departamento departamento;
    private int mes;
    private int anio;
    private int numeroFolio;
    private String nombreGastoAdministracion;
    private Date fechaGastoAdministracion;
    private Date fechaIngreso;
    private int valor;
    private String observacion;

    public GastoAdministracionMensual() {
    }

    public GastoAdministracionMensual(Departamento departamento, int mes, int anio, int numeroFolio, String nombreGastoAdministracion, Date fechaGastoAdministracion, Date fechaIngreso, int valor) {
        this.departamento = departamento;
        this.mes = mes;
        this.anio = anio;
        this.numeroFolio = numeroFolio;
        this.nombreGastoAdministracion = nombreGastoAdministracion;
        this.fechaGastoAdministracion = fechaGastoAdministracion;
        this.fechaIngreso = fechaIngreso;
        this.valor = valor;
    }

    public GastoAdministracionMensual(Departamento departamento, int mes, int anio, int numeroFolio, String nombreGastoAdministracion, Date fechaGastoAdministracion, Date fechaIngreso, int valor, String observacion) {
        this.departamento = departamento;
        this.mes = mes;
        this.anio = anio;
        this.numeroFolio = numeroFolio;
        this.nombreGastoAdministracion = nombreGastoAdministracion;
        this.fechaGastoAdministracion = fechaGastoAdministracion;
        this.fechaIngreso = fechaIngreso;
        this.valor = valor;
        this.observacion = observacion;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_gasto_administracion_mensual", unique = true, nullable = false)
    public Integer getIdGastoAdministracionMensual() {
        return this.idGastoAdministracionMensual;
    }

    public void setIdGastoAdministracionMensual(Integer idGastoAdministracionMensual) {
        this.idGastoAdministracionMensual = idGastoAdministracionMensual;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_departamento", nullable = false)
    public Departamento getDepartamento() {
        return this.departamento;
    }

    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    @Column(name = "mes", nullable = false)
    public int getMes() {
        return this.mes;
    }

    public void setMes(int mes) {
        this.mes = mes;
    }

    @Column(name = "anio", nullable = false)
    public int getAnio() {
        return this.anio;
    }

    public void setAnio(int anio) {
        this.anio = anio;
    }

    @Column(name = "numero_folio", nullable = false)
    public int getNumeroFolio() {
        return this.numeroFolio;
    }

    public void setNumeroFolio(int numeroFolio) {
        this.numeroFolio = numeroFolio;
    }

    @Column(name = "nombre_gasto_administracion", nullable = false, length = 45)
    public String getNombreGastoAdministracion() {
        return this.nombreGastoAdministracion;
    }

    public void setNombreGastoAdministracion(String nombreGastoAdministracion) {
        this.nombreGastoAdministracion = nombreGastoAdministracion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_gasto_administracion", nullable = false, length = 10)
    public Date getFechaGastoAdministracion() {
        return this.fechaGastoAdministracion;
    }

    public void setFechaGastoAdministracion(Date fechaGastoAdministracion) {
        this.fechaGastoAdministracion = fechaGastoAdministracion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_ingreso", nullable = false, length = 10)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }

    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    @Column(name = "valor", nullable = false)
    public int getValor() {
        return this.valor;
    }

    public void setValor(int valor) {
        this.valor = valor;
    }

    @Column(name = "observacion")
    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 97 * hash + Objects.hashCode(this.idGastoAdministracionMensual);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final GastoAdministracionMensual other = (GastoAdministracionMensual) obj;
        if (!Objects.equals(this.idGastoAdministracionMensual, other.idGastoAdministracionMensual)) {
            return false;
        }
        return true;
    }

}
