package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GrupoAsignacionTrabajador generated by hbm2java
 */
@Entity
@Table(name="grupo_asignacion_trabajador"
    ,catalog="sigf_v1"
)
public class GrupoAsignacionTrabajador  implements java.io.Serializable {


     private Integer idGrupoAsignacionTrabajador;
     private AsignacionFamiliar asignacionFamiliar;
     private int sueldoAsignacionTrabajador;
     private Set<Trabajador> trabajadors = new HashSet<Trabajador>(0);

    public GrupoAsignacionTrabajador() {
    }

	
    public GrupoAsignacionTrabajador(AsignacionFamiliar asignacionFamiliar, int sueldoAsignacionTrabajador) {
        this.asignacionFamiliar = asignacionFamiliar;
        this.sueldoAsignacionTrabajador = sueldoAsignacionTrabajador;
    }
    public GrupoAsignacionTrabajador(AsignacionFamiliar asignacionFamiliar, int sueldoAsignacionTrabajador, Set<Trabajador> trabajadors) {
       this.asignacionFamiliar = asignacionFamiliar;
       this.sueldoAsignacionTrabajador = sueldoAsignacionTrabajador;
       this.trabajadors = trabajadors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_grupo_asignacion_trabajador", unique=true, nullable=false)
    public Integer getIdGrupoAsignacionTrabajador() {
        return this.idGrupoAsignacionTrabajador;
    }
    
    public void setIdGrupoAsignacionTrabajador(Integer idGrupoAsignacionTrabajador) {
        this.idGrupoAsignacionTrabajador = idGrupoAsignacionTrabajador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_asignacion_familiar", nullable=false)
    public AsignacionFamiliar getAsignacionFamiliar() {
        return this.asignacionFamiliar;
    }
    
    public void setAsignacionFamiliar(AsignacionFamiliar asignacionFamiliar) {
        this.asignacionFamiliar = asignacionFamiliar;
    }

    
    @Column(name="sueldo_asignacion_trabajador", nullable=false)
    public int getSueldoAsignacionTrabajador() {
        return this.sueldoAsignacionTrabajador;
    }
    
    public void setSueldoAsignacionTrabajador(int sueldoAsignacionTrabajador) {
        this.sueldoAsignacionTrabajador = sueldoAsignacionTrabajador;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoAsignacionTrabajador")
    public Set<Trabajador> getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set<Trabajador> trabajadors) {
        this.trabajadors = trabajadors;
    }




}


