package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Guia generated by hbm2java
 */
@Entity
@Table(name="guia"
    ,catalog="sigf_v1"
)
public class Guia  implements java.io.Serializable {


     private Integer idGuia;
     private Bus bus;
     private EstadoGuia estadoGuia;
     private ProcesoRecaudacion procesoRecaudacion;
     private Trabajador trabajador;
     private int folio;
     private Date fechaGuia;
     private Date fechaIngresoGuia;
     private Date fechaRecaudacion;
     private Integer totalIngresos;
     private Integer totalEgresos;
     private Integer viajeEspecial;
     private Integer otrosIngresos;
     private int saldo;
     private Integer numeroVueltas;
     private Integer turno;
     private String observacion;
     private Boolean recaudada;
     private Set<EgresoGuia> egresoGuias = new HashSet<EgresoGuia>(0);
     private Set<SerieBoletoGuia> serieBoletoGuias = new HashSet<SerieBoletoGuia>(0);
     private Set<VentaBoletoGuia> ventaBoletoGuias = new HashSet<VentaBoletoGuia>(0);

    public Guia() {
        this.saldo = 0;
        this.totalIngresos = 0;
        this.totalEgresos = 0;
        this.viajeEspecial = 0;
        this.otrosIngresos = 0;
        this.numeroVueltas = 5;
        this.turno = 1;
    }

	
    public Guia(Bus bus, EstadoGuia estadoGuia, ProcesoRecaudacion procesoRecaudacion, Trabajador trabajador, int folio, Date fechaGuia, int saldo) {
        this.bus = bus;
        this.estadoGuia = estadoGuia;
        this.procesoRecaudacion = procesoRecaudacion;
        this.trabajador = trabajador;
        this.folio = folio;
        this.fechaGuia = fechaGuia;
        this.saldo = saldo;
    }
    public Guia(Bus bus, EstadoGuia estadoGuia, ProcesoRecaudacion procesoRecaudacion, Trabajador trabajador, int folio, Date fechaGuia, Date fechaIngresoGuia, Date fechaRecaudacion, Integer totalIngresos, Integer totalEgresos, Integer viajeEspecial, Integer otrosIngresos, int saldo, Integer numeroVueltas, Integer turno, String observacion, Boolean recaudada, Set<EgresoGuia> egresoGuias, Set<SerieBoletoGuia> serieBoletoGuias, Set<VentaBoletoGuia> ventaBoletoGuias) {
       this.bus = bus;
       this.estadoGuia = estadoGuia;
       this.procesoRecaudacion = procesoRecaudacion;
       this.trabajador = trabajador;
       this.folio = folio;
       this.fechaGuia = fechaGuia;
       this.fechaIngresoGuia = fechaIngresoGuia;
       this.fechaRecaudacion = fechaRecaudacion;
       this.totalIngresos = totalIngresos;
       this.totalEgresos = totalEgresos;
       this.viajeEspecial = viajeEspecial;
       this.otrosIngresos = otrosIngresos;
       this.saldo = saldo;
       this.numeroVueltas = numeroVueltas;
       this.turno = turno;
       this.observacion = observacion;
       this.recaudada = recaudada;
       this.egresoGuias = egresoGuias;
       this.serieBoletoGuias = serieBoletoGuias;
       this.ventaBoletoGuias = ventaBoletoGuias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_guia", unique=true, nullable=false)
    public Integer getIdGuia() {
        return this.idGuia;
    }
    
    public void setIdGuia(Integer idGuia) {
        this.idGuia = idGuia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_bus", nullable=false)
    public Bus getBus() {
        return this.bus;
    }
    
    public void setBus(Bus bus) {
        this.bus = bus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_estado", nullable=false)
    public EstadoGuia getEstadoGuia() {
        return this.estadoGuia;
    }
    
    public void setEstadoGuia(EstadoGuia estadoGuia) {
        this.estadoGuia = estadoGuia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_proceso_recuadacion", nullable=false)
    public ProcesoRecaudacion getProcesoRecaudacion() {
        return this.procesoRecaudacion;
    }
    
    public void setProcesoRecaudacion(ProcesoRecaudacion procesoRecaudacion) {
        this.procesoRecaudacion = procesoRecaudacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_trabajador", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    
    @Column(name="folio", nullable=false)
    public int getFolio() {
        return this.folio;
    }
    
    public void setFolio(int folio) {
        this.folio = folio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_guia", nullable=false, length=10)
    public Date getFechaGuia() {
        return this.fechaGuia;
    }
    
    public void setFechaGuia(Date fechaGuia) {
        this.fechaGuia = fechaGuia;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_ingreso_guia", length=19)
    public Date getFechaIngresoGuia() {
        return this.fechaIngresoGuia;
    }
    
    public void setFechaIngresoGuia(Date fechaIngresoGuia) {
        this.fechaIngresoGuia = fechaIngresoGuia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_recaudacion", length=10)
    public Date getFechaRecaudacion() {
        return this.fechaRecaudacion;
    }
    
    public void setFechaRecaudacion(Date fechaRecaudacion) {
        this.fechaRecaudacion = fechaRecaudacion;
    }

    
    @Column(name="total_ingresos")
    public Integer getTotalIngresos() {
        return this.totalIngresos;
    }
    
    public void setTotalIngresos(Integer totalIngresos) {
        this.totalIngresos = totalIngresos;
    }

    
    @Column(name="total_egresos")
    public Integer getTotalEgresos() {
        return this.totalEgresos;
    }
    
    public void setTotalEgresos(Integer totalEgresos) {
        this.totalEgresos = totalEgresos;
    }

    
    @Column(name="viaje_especial")
    public Integer getViajeEspecial() {
        return this.viajeEspecial;
    }
    
    public void setViajeEspecial(Integer viajeEspecial) {
        this.viajeEspecial = viajeEspecial;
    }

    
    @Column(name="otros_ingresos")
    public Integer getOtrosIngresos() {
        return this.otrosIngresos;
    }
    
    public void setOtrosIngresos(Integer otrosIngresos) {
        this.otrosIngresos = otrosIngresos;
    }

    
    @Column(name="saldo", nullable=false)
    public int getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(int saldo) {
        this.saldo = saldo;
    }

    
    @Column(name="numero_vueltas")
    public Integer getNumeroVueltas() {
        return this.numeroVueltas;
    }
    
    public void setNumeroVueltas(Integer numeroVueltas) {
        this.numeroVueltas = numeroVueltas;
    }

    
    @Column(name="turno")
    public Integer getTurno() {
        return this.turno;
    }
    
    public void setTurno(Integer turno) {
        this.turno = turno;
    }

    
    @Column(name="observacion", length=100)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="recaudada")
    public Boolean getRecaudada() {
        return this.recaudada;
    }
    
    public void setRecaudada(Boolean recaudada) {
        this.recaudada = recaudada;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="guia")
    public Set<EgresoGuia> getEgresoGuias() {
        return this.egresoGuias;
    }
    
    public void setEgresoGuias(Set<EgresoGuia> egresoGuias) {
        this.egresoGuias = egresoGuias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="guia")
    public Set<SerieBoletoGuia> getSerieBoletoGuias() {
        return this.serieBoletoGuias;
    }
    
    public void setSerieBoletoGuias(Set<SerieBoletoGuia> serieBoletoGuias) {
        this.serieBoletoGuias = serieBoletoGuias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="guia")
    public Set<VentaBoletoGuia> getVentaBoletoGuias() {
        return this.ventaBoletoGuias;
    }
    
    public void setVentaBoletoGuias(Set<VentaBoletoGuia> ventaBoletoGuias) {
        this.ventaBoletoGuias = ventaBoletoGuias;
    }




}


