package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HorarioServicio generated by hbm2java
 */
@Entity
@Table(name="horario_servicio"
    ,catalog="sigf_v1"
)
public class HorarioServicio  implements java.io.Serializable {


     private Integer idHorarioServicio;
     private Servicio servicio;
     private TipoEstacionalidad tipoEstacionalidad;
     private String nombre;
     private Date desde;
     private Date hasta;
     private Boolean lunes;
     private Boolean martes;
     private Boolean miercoles;
     private Boolean jueves;
     private Boolean viernes;
     private Boolean sabado;
     private Boolean domingo;
     private Set<ControlHorarioServicio> controlHorarioServicios = new HashSet<ControlHorarioServicio>(0);

    public HorarioServicio() {
    }

	
    public HorarioServicio(Servicio servicio, TipoEstacionalidad tipoEstacionalidad, String nombre, Date desde, Date hasta) {
        this.servicio = servicio;
        this.tipoEstacionalidad = tipoEstacionalidad;
        this.nombre = nombre;
        this.desde = desde;
        this.hasta = hasta;
    }
    public HorarioServicio(Servicio servicio, TipoEstacionalidad tipoEstacionalidad, String nombre, Date desde, Date hasta, Boolean lunes, Boolean martes, Boolean miercoles, Boolean jueves, Boolean viernes, Boolean sabado, Boolean domingo, Set<ControlHorarioServicio> controlHorarioServicios) {
       this.servicio = servicio;
       this.tipoEstacionalidad = tipoEstacionalidad;
       this.nombre = nombre;
       this.desde = desde;
       this.hasta = hasta;
       this.lunes = lunes;
       this.martes = martes;
       this.miercoles = miercoles;
       this.jueves = jueves;
       this.viernes = viernes;
       this.sabado = sabado;
       this.domingo = domingo;
       this.controlHorarioServicios = controlHorarioServicios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_horario_servicio", unique=true, nullable=false)
    public Integer getIdHorarioServicio() {
        return this.idHorarioServicio;
    }
    
    public void setIdHorarioServicio(Integer idHorarioServicio) {
        this.idHorarioServicio = idHorarioServicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_servicio", nullable=false)
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_estacionalidad", nullable=false)
    public TipoEstacionalidad getTipoEstacionalidad() {
        return this.tipoEstacionalidad;
    }
    
    public void setTipoEstacionalidad(TipoEstacionalidad tipoEstacionalidad) {
        this.tipoEstacionalidad = tipoEstacionalidad;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="desde", nullable=false, length=8)
    public Date getDesde() {
        return this.desde;
    }
    
    public void setDesde(Date desde) {
        this.desde = desde;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="hasta", nullable=false, length=8)
    public Date getHasta() {
        return this.hasta;
    }
    
    public void setHasta(Date hasta) {
        this.hasta = hasta;
    }

    
    @Column(name="lunes")
    public Boolean getLunes() {
        return this.lunes;
    }
    
    public void setLunes(Boolean lunes) {
        this.lunes = lunes;
    }

    
    @Column(name="martes")
    public Boolean getMartes() {
        return this.martes;
    }
    
    public void setMartes(Boolean martes) {
        this.martes = martes;
    }

    
    @Column(name="miercoles")
    public Boolean getMiercoles() {
        return this.miercoles;
    }
    
    public void setMiercoles(Boolean miercoles) {
        this.miercoles = miercoles;
    }

    
    @Column(name="jueves")
    public Boolean getJueves() {
        return this.jueves;
    }
    
    public void setJueves(Boolean jueves) {
        this.jueves = jueves;
    }

    
    @Column(name="viernes")
    public Boolean getViernes() {
        return this.viernes;
    }
    
    public void setViernes(Boolean viernes) {
        this.viernes = viernes;
    }

    
    @Column(name="sabado")
    public Boolean getSabado() {
        return this.sabado;
    }
    
    public void setSabado(Boolean sabado) {
        this.sabado = sabado;
    }

    
    @Column(name="domingo")
    public Boolean getDomingo() {
        return this.domingo;
    }
    
    public void setDomingo(Boolean domingo) {
        this.domingo = domingo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="horarioServicio")
    public Set<ControlHorarioServicio> getControlHorarioServicios() {
        return this.controlHorarioServicios;
    }
    
    public void setControlHorarioServicios(Set<ControlHorarioServicio> controlHorarioServicios) {
        this.controlHorarioServicios = controlHorarioServicios;
    }




}


