package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InstitucionSalud generated by hbm2java
 */
@Entity
@Table(name="institucion_salud"
    ,catalog="sigf_v1"
)
public class InstitucionSalud  implements java.io.Serializable {


     private Integer idInstitucionSalud;
     private String nombreInstitucionSalud;
     private BigDecimal comision;
     private BigDecimal porcentajeDescuento;
     private Set<Trabajador> trabajadors = new HashSet<Trabajador>(0);

    public InstitucionSalud() {
    }

	
    public InstitucionSalud(String nombreInstitucionSalud, BigDecimal porcentajeDescuento) {
        this.nombreInstitucionSalud = nombreInstitucionSalud;
        this.porcentajeDescuento = porcentajeDescuento;
    }
    public InstitucionSalud(String nombreInstitucionSalud, BigDecimal comision, BigDecimal porcentajeDescuento, Set<Trabajador> trabajadors) {
       this.nombreInstitucionSalud = nombreInstitucionSalud;
       this.comision = comision;
       this.porcentajeDescuento = porcentajeDescuento;
       this.trabajadors = trabajadors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_institucion_salud", unique=true, nullable=false)
    public Integer getIdInstitucionSalud() {
        return this.idInstitucionSalud;
    }
    
    public void setIdInstitucionSalud(Integer idInstitucionSalud) {
        this.idInstitucionSalud = idInstitucionSalud;
    }

    
    @Column(name="nombre_institucion_salud", nullable=false)
    public String getNombreInstitucionSalud() {
        return this.nombreInstitucionSalud;
    }
    
    public void setNombreInstitucionSalud(String nombreInstitucionSalud) {
        this.nombreInstitucionSalud = nombreInstitucionSalud;
    }

    
    @Column(name="comision", precision=10, scale=5)
    public BigDecimal getComision() {
        return this.comision;
    }
    
    public void setComision(BigDecimal comision) {
        this.comision = comision;
    }

    
    @Column(name="porcentaje_descuento", nullable=false, precision=10, scale=5)
    public BigDecimal getPorcentajeDescuento() {
        return this.porcentajeDescuento;
    }
    
    public void setPorcentajeDescuento(BigDecimal porcentajeDescuento) {
        this.porcentajeDescuento = porcentajeDescuento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="institucionSalud")
    public Set<Trabajador> getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set<Trabajador> trabajadors) {
        this.trabajadors = trabajadors;
    }




}


