package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IntervalosAdministracion generated by hbm2java
 */
@Entity
@Table(name="intervalos_administracion"
    ,catalog="sigf_v1"
)
public class IntervalosAdministracion  implements java.io.Serializable {


     private Integer idIntervalosAdministracion;
     private String nombreIntervaloAdministracion;
     private int desde;
     private int hasta;
     private Set<DetalleIntervalosMensual> detalleIntervalosMensuals = new HashSet<DetalleIntervalosMensual>(0);

    public IntervalosAdministracion() {
    }

	
    public IntervalosAdministracion(String nombreIntervaloAdministracion, int desde, int hasta) {
        this.nombreIntervaloAdministracion = nombreIntervaloAdministracion;
        this.desde = desde;
        this.hasta = hasta;
    }
    public IntervalosAdministracion(String nombreIntervaloAdministracion, int desde, int hasta, Set<DetalleIntervalosMensual> detalleIntervalosMensuals) {
       this.nombreIntervaloAdministracion = nombreIntervaloAdministracion;
       this.desde = desde;
       this.hasta = hasta;
       this.detalleIntervalosMensuals = detalleIntervalosMensuals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_intervalos_administracion", unique=true, nullable=false)
    public Integer getIdIntervalosAdministracion() {
        return this.idIntervalosAdministracion;
    }
    
    public void setIdIntervalosAdministracion(Integer idIntervalosAdministracion) {
        this.idIntervalosAdministracion = idIntervalosAdministracion;
    }

    
    @Column(name="nombre_intervalo_administracion", nullable=false, length=45)
    public String getNombreIntervaloAdministracion() {
        return this.nombreIntervaloAdministracion;
    }
    
    public void setNombreIntervaloAdministracion(String nombreIntervaloAdministracion) {
        this.nombreIntervaloAdministracion = nombreIntervaloAdministracion;
    }

    
    @Column(name="desde", nullable=false)
    public int getDesde() {
        return this.desde;
    }
    
    public void setDesde(int desde) {
        this.desde = desde;
    }

    
    @Column(name="hasta", nullable=false)
    public int getHasta() {
        return this.hasta;
    }
    
    public void setHasta(int hasta) {
        this.hasta = hasta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="intervalosAdministracion")
    public Set<DetalleIntervalosMensual> getDetalleIntervalosMensuals() {
        return this.detalleIntervalosMensuals;
    }
    
    public void setDetalleIntervalosMensuals(Set<DetalleIntervalosMensual> detalleIntervalosMensuals) {
        this.detalleIntervalosMensuals = detalleIntervalosMensuals;
    }




}


