package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InventarioInterno generated by hbm2java
 */
@Entity
@Table(name = "inventario_interno",
         catalog = "sigf_v1"
)
public class InventarioInterno implements java.io.Serializable {

    private Integer idInventarioInterno;
    private Boleto boleto;
    private int serie;
    private String identificador;
    private int cantidadRollos;
    private Boolean estado;
    private Set<DetalleVentaBoleto> detalleVentaBoletos = new HashSet<DetalleVentaBoleto>(0);

    public InventarioInterno() {
    }

    public InventarioInterno(Boleto boleto, int serie, int cantidadRollos) {
        this.boleto = boleto;
        this.serie = serie;
        this.cantidadRollos = cantidadRollos;
    }

    public InventarioInterno(Boleto boleto, int serie, String identificador, int cantidadRollos, Boolean estado, Set<DetalleVentaBoleto> detalleVentaBoletos) {
        this.boleto = boleto;
        this.serie = serie;
        this.identificador = identificador;
        this.cantidadRollos = cantidadRollos;
        this.estado = estado;
        this.detalleVentaBoletos = detalleVentaBoletos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_inventario_interno", unique = true, nullable = false)
    public Integer getIdInventarioInterno() {
        return this.idInventarioInterno;
    }

    public void setIdInventarioInterno(Integer idInventarioInterno) {
        this.idInventarioInterno = idInventarioInterno;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_boleto", nullable = false)
    public Boleto getBoleto() {
        return this.boleto;
    }

    public void setBoleto(Boleto boleto) {
        this.boleto = boleto;
    }

    @Column(name = "serie", nullable = false)
    public int getSerie() {
        return this.serie;
    }

    public void setSerie(int serie) {
        this.serie = serie;
    }

    @Column(name = "identificador", length = 45)
    public String getIdentificador() {
        return this.identificador;
    }

    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }

    @Column(name = "cantidad_rollos", nullable = false)
    public int getCantidadRollos() {
        return this.cantidadRollos;
    }

    public void setCantidadRollos(int cantidadRollos) {
        this.cantidadRollos = cantidadRollos;
    }

    @Column(name = "estado")
    public Boolean getEstado() {
        return this.estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "inventarioInterno")
    public Set<DetalleVentaBoleto> getDetalleVentaBoletos() {
        return this.detalleVentaBoletos;
    }

    public void setDetalleVentaBoletos(Set<DetalleVentaBoleto> detalleVentaBoletos) {
        this.detalleVentaBoletos = detalleVentaBoletos;
    }

    @Override
    public String toString() {
        return identificador + serie;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 41 * hash + Objects.hashCode(this.idInventarioInterno);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final InventarioInterno other = (InventarioInterno) obj;
        if (!Objects.equals(this.idInventarioInterno, other.idInventarioInterno)) {
            return false;
        }
        return true;
    }

}
