package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InventarioTerminal generated by hbm2java
 */
@Entity
@Table(name="inventario_terminal"
    ,catalog="sigf_v1"
)
public class InventarioTerminal  implements java.io.Serializable {


     private Integer idInventarioTerminal;
     private Boleto boleto;
     private Terminal terminal;
     private Boolean estado;
     private int serie;
     private String identificador;
     private Set<VentaBoletoGuia> ventaBoletoGuias = new HashSet<VentaBoletoGuia>(0);

    public InventarioTerminal() {
    }

	
    public InventarioTerminal(Boleto boleto, Terminal terminal, int serie, String identificador) {
        this.boleto = boleto;
        this.terminal = terminal;
        this.serie = serie;
        this.identificador = identificador;
    }
    public InventarioTerminal(Boleto boleto, Terminal terminal, Boolean estado, int serie, String identificador, Set<VentaBoletoGuia> ventaBoletoGuias) {
       this.boleto = boleto;
       this.terminal = terminal;
       this.estado = estado;
       this.serie = serie;
       this.identificador = identificador;
       this.ventaBoletoGuias = ventaBoletoGuias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_inventario_terminal", unique=true, nullable=false)
    public Integer getIdInventarioTerminal() {
        return this.idInventarioTerminal;
    }
    
    public void setIdInventarioTerminal(Integer idInventarioTerminal) {
        this.idInventarioTerminal = idInventarioTerminal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_boleto", nullable=false)
    public Boleto getBoleto() {
        return this.boleto;
    }
    
    public void setBoleto(Boleto boleto) {
        this.boleto = boleto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_terminal", nullable=false)
    public Terminal getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(Terminal terminal) {
        this.terminal = terminal;
    }

    
    @Column(name="estado")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    
    @Column(name="serie", nullable=false)
    public int getSerie() {
        return this.serie;
    }
    
    public void setSerie(int serie) {
        this.serie = serie;
    }

    
    @Column(name="identificador", nullable=false, length=10)
    public String getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="inventarioTerminal")
    public Set<VentaBoletoGuia> getVentaBoletoGuias() {
        return this.ventaBoletoGuias;
    }
    
    public void setVentaBoletoGuias(Set<VentaBoletoGuia> ventaBoletoGuias) {
        this.ventaBoletoGuias = ventaBoletoGuias;
    }




}


