package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LiquidacionEmpresa generated by hbm2java
 */
@Entity
@Table(name="liquidacion_empresa"
    ,catalog="sigf_v1"
)
public class LiquidacionEmpresa  implements java.io.Serializable {


     private Integer idLiquidacionEmpresa;
     private Empresa empresa;
     private int mes;
     private int anio;
     private Date fechaEmision;
     private Date fechaPago;
     private int totalAbonos;
     private int totalCargos;
     private int saldo;
     private Set<AbonoLiquidacion> abonoLiquidacions = new HashSet<AbonoLiquidacion>(0);
     private Set<CargoLiquidacion> cargoLiquidacions = new HashSet<CargoLiquidacion>(0);

    public LiquidacionEmpresa() {
    }

	
    public LiquidacionEmpresa(Empresa empresa, int mes, int anio, Date fechaEmision, Date fechaPago, int totalAbonos, int totalCargos, int saldo) {
        this.empresa = empresa;
        this.mes = mes;
        this.anio = anio;
        this.fechaEmision = fechaEmision;
        this.fechaPago = fechaPago;
        this.totalAbonos = totalAbonos;
        this.totalCargos = totalCargos;
        this.saldo = saldo;
    }
    public LiquidacionEmpresa(Empresa empresa, int mes, int anio, Date fechaEmision, Date fechaPago, int totalAbonos, int totalCargos, int saldo, Set<AbonoLiquidacion> abonoLiquidacions, Set<CargoLiquidacion> cargoLiquidacions) {
       this.empresa = empresa;
       this.mes = mes;
       this.anio = anio;
       this.fechaEmision = fechaEmision;
       this.fechaPago = fechaPago;
       this.totalAbonos = totalAbonos;
       this.totalCargos = totalCargos;
       this.saldo = saldo;
       this.abonoLiquidacions = abonoLiquidacions;
       this.cargoLiquidacions = cargoLiquidacions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_liquidacion_empresa", unique=true, nullable=false)
    public Integer getIdLiquidacionEmpresa() {
        return this.idLiquidacionEmpresa;
    }
    
    public void setIdLiquidacionEmpresa(Integer idLiquidacionEmpresa) {
        this.idLiquidacionEmpresa = idLiquidacionEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_empresa", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="mes", nullable=false)
    public int getMes() {
        return this.mes;
    }
    
    public void setMes(int mes) {
        this.mes = mes;
    }

    
    @Column(name="anio", nullable=false)
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_emision", nullable=false, length=10)
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_pago", nullable=false, length=10)
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }

    
    @Column(name="total_abonos", nullable=false)
    public int getTotalAbonos() {
        return this.totalAbonos;
    }
    
    public void setTotalAbonos(int totalAbonos) {
        this.totalAbonos = totalAbonos;
    }

    
    @Column(name="total_cargos", nullable=false)
    public int getTotalCargos() {
        return this.totalCargos;
    }
    
    public void setTotalCargos(int totalCargos) {
        this.totalCargos = totalCargos;
    }

    
    @Column(name="saldo", nullable=false)
    public int getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(int saldo) {
        this.saldo = saldo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="liquidacionEmpresa")
    public Set<AbonoLiquidacion> getAbonoLiquidacions() {
        return this.abonoLiquidacions;
    }
    
    public void setAbonoLiquidacions(Set<AbonoLiquidacion> abonoLiquidacions) {
        this.abonoLiquidacions = abonoLiquidacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="liquidacionEmpresa")
    public Set<CargoLiquidacion> getCargoLiquidacions() {
        return this.cargoLiquidacions;
    }
    
    public void setCargoLiquidacions(Set<CargoLiquidacion> cargoLiquidacions) {
        this.cargoLiquidacions = cargoLiquidacions;
    }




}


