package com.areatecnica.sigf_v1.entities;
// Generated 26-01-2017 15:49:07 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name = "log", catalog = "sigf_v1"
)
public class Log implements java.io.Serializable {

    private Integer idLog;
    private Privilegio privilegio;
    private Usuario usuario;
    private String tipoAccion;
    private String descripcionLog;
    private Date fechaRegistroLog;

    public Log() {
    }

    public Log(Privilegio privilegio, Usuario usuario, String tipoAccion, String descripcionLog, Date fechaRegistroLog) {
        this.privilegio = privilegio;
        this.usuario = usuario;
        this.tipoAccion = tipoAccion;
        this.descripcionLog = descripcionLog;
        this.fechaRegistroLog = fechaRegistroLog;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_log", unique = true, nullable = false)
    public Integer getIdLog() {
        return this.idLog;
    }

    public void setIdLog(Integer idLog) {
        this.idLog = idLog;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_privilegio", nullable = false)
    public Privilegio getPrivilegio() {
        return this.privilegio;
    }

    public void setPrivilegio(Privilegio privilegio) {
        this.privilegio = privilegio;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_usuario", nullable = false)
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Column(name = "tipo_accion", nullable = false, length = 45)
    public String getTipoAccion() {
        return this.tipoAccion;
    }

    public void setTipoAccion(String tipoAccion) {
        this.tipoAccion = tipoAccion;
    }

    @Column(name = "descripcion_log", nullable = false)
    public String getDescripcionLog() {
        return this.descripcionLog;
    }

    public void setDescripcionLog(String descripcionLog) {
        this.descripcionLog = descripcionLog;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_registro_log", nullable = false, length = 19)
    public Date getFechaRegistroLog() {
        return this.fechaRegistroLog;
    }

    public void setFechaRegistroLog(Date fechaRegistroLog) {
        this.fechaRegistroLog = fechaRegistroLog;
    }

}
