package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MarcaBus generated by hbm2java
 */
@Entity
@Table(name = "marca_bus", catalog = "sigf_v1"
)
public class MarcaBus implements java.io.Serializable {

    private Integer idMarcasBus;
    private String nombreMarcaBus;
    private Set<ModeloMarcaBus> modeloMarcaBuses = new HashSet<ModeloMarcaBus>(0);

    public MarcaBus() {
    }

    public MarcaBus(String nombreMarcaBus) {
        this.nombreMarcaBus = nombreMarcaBus;
    }

    public MarcaBus(String nombreMarcaBus, Set<ModeloMarcaBus> modeloMarcaBuses) {
        this.nombreMarcaBus = nombreMarcaBus;
        this.modeloMarcaBuses = modeloMarcaBuses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_marcas_bus", unique = true, nullable = false)
    public Integer getIdMarcasBus() {
        return this.idMarcasBus;
    }

    public void setIdMarcasBus(Integer idMarcasBus) {
        this.idMarcasBus = idMarcasBus;
    }

    @Column(name = "nombre_marca_bus", nullable = false, length = 45)
    public String getNombreMarcaBus() {
        return this.nombreMarcaBus;
    }

    public void setNombreMarcaBus(String nombreMarcaBus) {
        this.nombreMarcaBus = nombreMarcaBus;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "marcaBus")
    public Set<ModeloMarcaBus> getModeloMarcaBuses() {
        return this.modeloMarcaBuses;
    }

    public void setModeloMarcaBuses(Set<ModeloMarcaBus> modeloMarcaBuses) {
        this.modeloMarcaBuses = modeloMarcaBuses;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idMarcasBus != null ? idMarcasBus.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof MarcaBus)) {
            return false;
        }
        MarcaBus other = (MarcaBus) object;
        if ((this.idMarcasBus == null && other.idMarcasBus != null) || (this.idMarcasBus != null && !this.idMarcasBus.equals(other.idMarcasBus))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return nombreMarcaBus;
    }

}
