package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModeloMarcaBus generated by hbm2java
 */
@Entity
@Table(name="modelo_marca_bus"
    ,catalog="sigf_v1"
)
public class ModeloMarcaBus  implements java.io.Serializable {


     private Integer idModeloMarcaBus;
     private MarcaBus marcaBus;
     private String nombreModeloMarcaBus;
     private Set<Bus> buses = new HashSet<Bus>(0);

    public ModeloMarcaBus() {
    }

	
    public ModeloMarcaBus(MarcaBus marcaBus, String nombreModeloMarcaBus) {
        this.marcaBus = marcaBus;
        this.nombreModeloMarcaBus = nombreModeloMarcaBus;
    }
    public ModeloMarcaBus(MarcaBus marcaBus, String nombreModeloMarcaBus, Set<Bus> buses) {
       this.marcaBus = marcaBus;
       this.nombreModeloMarcaBus = nombreModeloMarcaBus;
       this.buses = buses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_modelo_marca_bus", unique=true, nullable=false)
    public Integer getIdModeloMarcaBus() {
        return this.idModeloMarcaBus;
    }
    
    public void setIdModeloMarcaBus(Integer idModeloMarcaBus) {
        this.idModeloMarcaBus = idModeloMarcaBus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_marca_bus", nullable=false)
    public MarcaBus getMarcaBus() {
        return this.marcaBus;
    }
    
    public void setMarcaBus(MarcaBus marcaBus) {
        this.marcaBus = marcaBus;
    }

    
    @Column(name="nombre_modelo_marca_bus", nullable=false, length=45)
    public String getNombreModeloMarcaBus() {
        return this.nombreModeloMarcaBus;
    }
    
    public void setNombreModeloMarcaBus(String nombreModeloMarcaBus) {
        this.nombreModeloMarcaBus = nombreModeloMarcaBus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="modeloMarcaBus")
    public Set<Bus> getBuses() {
        return this.buses;
    }
    
    public void setBuses(Set<Bus> buses) {
        this.buses = buses;
    }




}


