package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MonedaPactadaInstitucionSalud generated by hbm2java
 */
@Entity
@Table(name = "moneda_pactada_institucion_salud", catalog = "sigf_v1"
)
public class MonedaPactadaInstitucionSalud implements java.io.Serializable {

    private Integer idMonedaSalud;
    private String nombreMonedaSalud;
    private Set<Trabajador> trabajadors = new HashSet<Trabajador>(0);

    public MonedaPactadaInstitucionSalud() {
    }

    public MonedaPactadaInstitucionSalud(String nombreMonedaSalud) {
        this.nombreMonedaSalud = nombreMonedaSalud;
    }

    public MonedaPactadaInstitucionSalud(String nombreMonedaSalud, Set<Trabajador> trabajadors) {
        this.nombreMonedaSalud = nombreMonedaSalud;
        this.trabajadors = trabajadors;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_moneda_salud", unique = true, nullable = false)
    public Integer getIdMonedaSalud() {
        return this.idMonedaSalud;
    }

    public void setIdMonedaSalud(Integer idMonedaSalud) {
        this.idMonedaSalud = idMonedaSalud;
    }

    @Column(name = "nombre_moneda_salud", nullable = false, length = 45)
    public String getNombreMonedaSalud() {
        return this.nombreMonedaSalud;
    }

    public void setNombreMonedaSalud(String nombreMonedaSalud) {
        this.nombreMonedaSalud = nombreMonedaSalud;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "monedaPactadaInstitucionSalud")
    public Set<Trabajador> getTrabajadors() {
        return this.trabajadors;
    }

    public void setTrabajadors(Set<Trabajador> trabajadors) {
        this.trabajadors = trabajadors;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idMonedaSalud != null ? idMonedaSalud.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof MonedaPactadaInstitucionSalud)) {
            return false;
        }
        MonedaPactadaInstitucionSalud other = (MonedaPactadaInstitucionSalud) object;
        if ((this.idMonedaSalud == null && other.idMonedaSalud != null) || (this.idMonedaSalud != null && !this.idMonedaSalud.equals(other.idMonedaSalud))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return nombreMonedaSalud;
    }

}
