package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MontoSindicatoTrabajador generated by hbm2java
 */
@Entity
@Table(name="monto_sindicato_trabajador"
    ,catalog="sigf_v1"
)
public class MontoSindicatoTrabajador  implements java.io.Serializable {


     private Integer idMontoSindicatoTrabajado;
     private SindicatoTrabajador sindicatoTrabajador;
     private int montoSindicatoTrabajador;
     private int mesLiquidacion;
     private int anioLiquidacion;

    public MontoSindicatoTrabajador() {
    }

    public MontoSindicatoTrabajador(SindicatoTrabajador sindicatoTrabajador, int montoSindicatoTrabajador, int mesLiquidacion, int anioLiquidacion) {
       this.sindicatoTrabajador = sindicatoTrabajador;
       this.montoSindicatoTrabajador = montoSindicatoTrabajador;
       this.mesLiquidacion = mesLiquidacion;
       this.anioLiquidacion = anioLiquidacion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_monto_sindicato_trabajado", unique=true, nullable=false)
    public Integer getIdMontoSindicatoTrabajado() {
        return this.idMontoSindicatoTrabajado;
    }
    
    public void setIdMontoSindicatoTrabajado(Integer idMontoSindicatoTrabajado) {
        this.idMontoSindicatoTrabajado = idMontoSindicatoTrabajado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sindicato_trabajador", nullable=false)
    public SindicatoTrabajador getSindicatoTrabajador() {
        return this.sindicatoTrabajador;
    }
    
    public void setSindicatoTrabajador(SindicatoTrabajador sindicatoTrabajador) {
        this.sindicatoTrabajador = sindicatoTrabajador;
    }

    
    @Column(name="monto_sindicato_trabajador", nullable=false)
    public int getMontoSindicatoTrabajador() {
        return this.montoSindicatoTrabajador;
    }
    
    public void setMontoSindicatoTrabajador(int montoSindicatoTrabajador) {
        this.montoSindicatoTrabajador = montoSindicatoTrabajador;
    }

    
    @Column(name="mes_liquidacion", nullable=false)
    public int getMesLiquidacion() {
        return this.mesLiquidacion;
    }
    
    public void setMesLiquidacion(int mesLiquidacion) {
        this.mesLiquidacion = mesLiquidacion;
    }

    
    @Column(name="anio_liquidacion", nullable=false)
    public int getAnioLiquidacion() {
        return this.anioLiquidacion;
    }
    
    public void setAnioLiquidacion(int anioLiquidacion) {
        this.anioLiquidacion = anioLiquidacion;
    }




}


