package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mutual generated by hbm2java
 */
@Entity
@Table(name="mutual"
    ,catalog="sigf_v1"
)
public class Mutual  implements java.io.Serializable {


     private Integer idMutual;
     private String nombreMutual;
     private BigDecimal comision;
     private BigDecimal porcentajeDescuento;
     private Set<Empresa> empresas = new HashSet<Empresa>(0);

    public Mutual() {
    }

	
    public Mutual(String nombreMutual, BigDecimal porcentajeDescuento) {
        this.nombreMutual = nombreMutual;
        this.porcentajeDescuento = porcentajeDescuento;
    }
    public Mutual(String nombreMutual, BigDecimal comision, BigDecimal porcentajeDescuento, Set<Empresa> empresas) {
       this.nombreMutual = nombreMutual;
       this.comision = comision;
       this.porcentajeDescuento = porcentajeDescuento;
       this.empresas = empresas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_mutual", unique=true, nullable=false)
    public Integer getIdMutual() {
        return this.idMutual;
    }
    
    public void setIdMutual(Integer idMutual) {
        this.idMutual = idMutual;
    }

    
    @Column(name="nombre_mutual", nullable=false)
    public String getNombreMutual() {
        return this.nombreMutual;
    }
    
    public void setNombreMutual(String nombreMutual) {
        this.nombreMutual = nombreMutual;
    }

    
    @Column(name="comision", precision=10, scale=5)
    public BigDecimal getComision() {
        return this.comision;
    }
    
    public void setComision(BigDecimal comision) {
        this.comision = comision;
    }

    
    @Column(name="porcentaje_descuento", nullable=false, precision=10, scale=5)
    public BigDecimal getPorcentajeDescuento() {
        return this.porcentajeDescuento;
    }
    
    public void setPorcentajeDescuento(BigDecimal porcentajeDescuento) {
        this.porcentajeDescuento = porcentajeDescuento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mutual")
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }




}


