package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ObservacionTrabajador generated by hbm2java
 */
@Entity
@Table(name="observacion_trabajador"
    ,catalog="sigf_v1"
)
public class ObservacionTrabajador  implements java.io.Serializable {


     private Integer idObservacionTrabajador;
     private Trabajador trabajador;
     private Date fecha;
     private Date fechaIngreso;
     private String descripcion;
     private String detalle;

    public ObservacionTrabajador() {
    }

    public ObservacionTrabajador(Trabajador trabajador, Date fecha, Date fechaIngreso, String descripcion, String detalle) {
       this.trabajador = trabajador;
       this.fecha = fecha;
       this.fechaIngreso = fechaIngreso;
       this.descripcion = descripcion;
       this.detalle = detalle;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_observacion_trabajador", unique=true, nullable=false)
    public Integer getIdObservacionTrabajador() {
        return this.idObservacionTrabajador;
    }
    
    public void setIdObservacionTrabajador(Integer idObservacionTrabajador) {
        this.idObservacionTrabajador = idObservacionTrabajador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_trabajador", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_ingreso", nullable=false, length=19)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="descripcion", nullable=false, length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="detalle", nullable=false, length=45)
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }




}


