package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OperadorTransporte generated by hbm2java
 */
@Entity
@Table(name="operador_transporte"
    ,catalog="sigf_v1"
)
public class OperadorTransporte  implements java.io.Serializable {


     private Integer idOperadorTransporte;
     private String rutOperador;
     private String nombreOperador;
     private Set<UnidadNegocio> unidadNegocios = new HashSet<UnidadNegocio>(0);

    public OperadorTransporte() {
    }

	
    public OperadorTransporte(String rutOperador, String nombreOperador) {
        this.rutOperador = rutOperador;
        this.nombreOperador = nombreOperador;
    }
    public OperadorTransporte(String rutOperador, String nombreOperador, Set<UnidadNegocio> unidadNegocios) {
       this.rutOperador = rutOperador;
       this.nombreOperador = nombreOperador;
       this.unidadNegocios = unidadNegocios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_operador_transporte", unique=true, nullable=false)
    public Integer getIdOperadorTransporte() {
        return this.idOperadorTransporte;
    }
    
    public void setIdOperadorTransporte(Integer idOperadorTransporte) {
        this.idOperadorTransporte = idOperadorTransporte;
    }

    
    @Column(name="rut_operador", nullable=false, length=9)
    public String getRutOperador() {
        return this.rutOperador;
    }
    
    public void setRutOperador(String rutOperador) {
        this.rutOperador = rutOperador;
    }

    
    @Column(name="nombre_operador", nullable=false, length=45)
    public String getNombreOperador() {
        return this.nombreOperador;
    }
    
    public void setNombreOperador(String nombreOperador) {
        this.nombreOperador = nombreOperador;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="operadorTransporte")
    public Set<UnidadNegocio> getUnidadNegocios() {
        return this.unidadNegocios;
    }
    
    public void setUnidadNegocios(Set<UnidadNegocio> unidadNegocios) {
        this.unidadNegocios = unidadNegocios;
    }




}


