package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ParametroCesantia generated by hbm2java
 */
@Entity
@Table(name="parametro_cesantia"
    ,catalog="sigf_v1"
)
public class ParametroCesantia  implements java.io.Serializable {


     private Integer idParametroCesantia;
     private BigDecimal empleador;
     private BigDecimal trabajador;

    public ParametroCesantia() {
    }

    public ParametroCesantia(BigDecimal empleador, BigDecimal trabajador) {
       this.empleador = empleador;
       this.trabajador = trabajador;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_parametro_cesantia", unique=true, nullable=false)
    public Integer getIdParametroCesantia() {
        return this.idParametroCesantia;
    }
    
    public void setIdParametroCesantia(Integer idParametroCesantia) {
        this.idParametroCesantia = idParametroCesantia;
    }

    
    @Column(name="empleador", nullable=false, precision=10)
    public BigDecimal getEmpleador() {
        return this.empleador;
    }
    
    public void setEmpleador(BigDecimal empleador) {
        this.empleador = empleador;
    }

    
    @Column(name="trabajador", nullable=false, precision=10)
    public BigDecimal getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(BigDecimal trabajador) {
        this.trabajador = trabajador;
    }




}


