package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ParentescoCarga generated by hbm2java
 */
@Entity
@Table(name="parentesco_carga"
    ,catalog="sigf_v1"
)
public class ParentescoCarga  implements java.io.Serializable {


     private Integer idParentescoCarga;
     private String nombreParentescoCarga;
     private Set<CargasTrabajador> cargasTrabajadors = new HashSet<CargasTrabajador>(0);

    public ParentescoCarga() {
    }

	
    public ParentescoCarga(String nombreParentescoCarga) {
        this.nombreParentescoCarga = nombreParentescoCarga;
    }
    public ParentescoCarga(String nombreParentescoCarga, Set<CargasTrabajador> cargasTrabajadors) {
       this.nombreParentescoCarga = nombreParentescoCarga;
       this.cargasTrabajadors = cargasTrabajadors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_parentesco_carga", unique=true, nullable=false)
    public Integer getIdParentescoCarga() {
        return this.idParentescoCarga;
    }
    
    public void setIdParentescoCarga(Integer idParentescoCarga) {
        this.idParentescoCarga = idParentescoCarga;
    }

    
    @Column(name="nombre_parentesco_carga", nullable=false, length=45)
    public String getNombreParentescoCarga() {
        return this.nombreParentescoCarga;
    }
    
    public void setNombreParentescoCarga(String nombreParentescoCarga) {
        this.nombreParentescoCarga = nombreParentescoCarga;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="parentescoCarga")
    public Set<CargasTrabajador> getCargasTrabajadors() {
        return this.cargasTrabajadors;
    }
    
    public void setCargasTrabajadors(Set<CargasTrabajador> cargasTrabajadors) {
        this.cargasTrabajadors = cargasTrabajadors;
    }




}


