package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name="position"
    ,catalog="sigf_v1"
)
public class Position  implements java.io.Serializable {


     private Integer id;
     private Device device;
     private String protocol;
     private Date serverTime;
     private Date deviceTime;
     private Date fixTime;
     private boolean valid;
     private double latitude;
     private double longitude;
     private float altitude;
     private float speed;
     private float course;
     private String address;
     private String attributes;

    public Position() {
    }

	
    public Position(Device device, Date serverTime, Date deviceTime, Date fixTime, boolean valid, double latitude, double longitude, float altitude, float speed, float course, String attributes) {
        this.device = device;
        this.serverTime = serverTime;
        this.deviceTime = deviceTime;
        this.fixTime = fixTime;
        this.valid = valid;
        this.latitude = latitude;
        this.longitude = longitude;
        this.altitude = altitude;
        this.speed = speed;
        this.course = course;
        this.attributes = attributes;
    }
    public Position(Device device, String protocol, Date serverTime, Date deviceTime, Date fixTime, boolean valid, double latitude, double longitude, float altitude, float speed, float course, String address, String attributes) {
       this.device = device;
       this.protocol = protocol;
       this.serverTime = serverTime;
       this.deviceTime = deviceTime;
       this.fixTime = fixTime;
       this.valid = valid;
       this.latitude = latitude;
       this.longitude = longitude;
       this.altitude = altitude;
       this.speed = speed;
       this.course = course;
       this.address = address;
       this.attributes = attributes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="deviceId", nullable=false)
    public Device getDevice() {
        return this.device;
    }
    
    public void setDevice(Device device) {
        this.device = device;
    }

    
    @Column(name="protocol", length=128)
    public String getProtocol() {
        return this.protocol;
    }
    
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="serverTime", nullable=false, length=19)
    public Date getServerTime() {
        return this.serverTime;
    }
    
    public void setServerTime(Date serverTime) {
        this.serverTime = serverTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deviceTime", nullable=false, length=19)
    public Date getDeviceTime() {
        return this.deviceTime;
    }
    
    public void setDeviceTime(Date deviceTime) {
        this.deviceTime = deviceTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fixTime", nullable=false, length=19)
    public Date getFixTime() {
        return this.fixTime;
    }
    
    public void setFixTime(Date fixTime) {
        this.fixTime = fixTime;
    }

    
    @Column(name="valid", nullable=false)
    public boolean isValid() {
        return this.valid;
    }
    
    public void setValid(boolean valid) {
        this.valid = valid;
    }

    
    @Column(name="latitude", nullable=false, precision=22, scale=0)
    public double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="longitude", nullable=false, precision=22, scale=0)
    public double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="altitude", nullable=false, precision=12, scale=0)
    public float getAltitude() {
        return this.altitude;
    }
    
    public void setAltitude(float altitude) {
        this.altitude = altitude;
    }

    
    @Column(name="speed", nullable=false, precision=12, scale=0)
    public float getSpeed() {
        return this.speed;
    }
    
    public void setSpeed(float speed) {
        this.speed = speed;
    }

    
    @Column(name="course", nullable=false, precision=12, scale=0)
    public float getCourse() {
        return this.course;
    }
    
    public void setCourse(float course) {
        this.course = course;
    }

    
    @Column(name="address", length=512)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="attributes", nullable=false, length=4096)
    public String getAttributes() {
        return this.attributes;
    }
    
    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }




}


