package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Privilegio generated by hbm2java
 */
@Entity
@Table(name = "privilegio", catalog = "sigf_v1"
)
public class Privilegio implements java.io.Serializable {

    private Integer idPrivilegio;
    private String nombrePrivilegio;
    private String descripcion;
    private Set<Log> logs = new HashSet<Log>(0);
    private Set<RolPrivilegio> rolPrivilegios = new HashSet<RolPrivilegio>(0);

    public Privilegio() {
    }

    public Privilegio(String nombrePrivilegio, String descripcion, Set<Log> logs, Set<RolPrivilegio> rolPrivilegios) {
        this.nombrePrivilegio = nombrePrivilegio;
        this.descripcion = descripcion;
        this.logs = logs;
        this.rolPrivilegios = rolPrivilegios;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_privilegio", unique = true, nullable = false)
    public Integer getIdPrivilegio() {
        return this.idPrivilegio;
    }

    public void setIdPrivilegio(Integer idPrivilegio) {
        this.idPrivilegio = idPrivilegio;
    }

    @Column(name = "nombre_privilegio", nullable = false)
    public String getNombrePrivilegio() {
        return this.nombrePrivilegio;
    }

    public void setNombrePrivilegio(String nombrePrivilegio) {
        this.nombrePrivilegio = nombrePrivilegio;
    }

    @Column(name = "descripcion", nullable = false)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "privilegio")
    public Set<Log> getLogs() {
        return this.logs;
    }

    public void setLogs(Set<Log> logs) {
        this.logs = logs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "privilegio")
    public Set<RolPrivilegio> getRolPrivilegios() {
        return this.rolPrivilegios;
    }

    public void setRolPrivilegios(Set<RolPrivilegio> rolPrivilegios) {
        this.rolPrivilegios = rolPrivilegios;
    }

}
