package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProcesoRecaudacion generated by hbm2java
 */
@Entity
@Table(name = "proceso_recaudacion", catalog = "sigf_v1"
)
public class ProcesoRecaudacion implements java.io.Serializable {

    private Integer idProcesoRecaudacion;
    private Usuario usuario;
    private String nombreProceso;
    private Date fechaCreacionProceso;
    private Boolean activo;
    private Set<ServicioProcesoRecaudacion> servicioProcesoRecaudacions = new HashSet<ServicioProcesoRecaudacion>(0);
    private Set<EgresoRecaudacion> egresoRecaudacions = new HashSet<EgresoRecaudacion>(0);
    private Set<Guia> guias = new HashSet<Guia>(0);

    public ProcesoRecaudacion() {
    }

    public ProcesoRecaudacion(Usuario usuario, String nombreProceso, Date fechaCreacionProceso) {
        this.usuario = usuario;
        this.nombreProceso = nombreProceso;
        this.fechaCreacionProceso = fechaCreacionProceso;
    }

    public ProcesoRecaudacion(Usuario usuario, String nombreProceso, Date fechaCreacionProceso, Boolean activo, Set<ServicioProcesoRecaudacion> servicioProcesoRecaudacions, Set<EgresoRecaudacion> egresoRecaudacions, Set<Guia> guias) {
        this.usuario = usuario;
        this.nombreProceso = nombreProceso;
        this.fechaCreacionProceso = fechaCreacionProceso;
        this.activo = activo;
        this.servicioProcesoRecaudacions = servicioProcesoRecaudacions;
        this.egresoRecaudacions = egresoRecaudacions;
        this.guias = guias;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_proceso_recaudacion", unique = true, nullable = false)
    public Integer getIdProcesoRecaudacion() {
        return this.idProcesoRecaudacion;
    }

    public void setIdProcesoRecaudacion(Integer idProcesoRecaudacion) {
        this.idProcesoRecaudacion = idProcesoRecaudacion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_usuario", nullable = false)
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Column(name = "nombre_proceso", nullable = false, length = 45)
    public String getNombreProceso() {
        return this.nombreProceso;
    }

    public void setNombreProceso(String nombreProceso) {
        this.nombreProceso = nombreProceso;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_creacion_proceso", nullable = false, length = 19)
    public Date getFechaCreacionProceso() {
        return this.fechaCreacionProceso;
    }

    public void setFechaCreacionProceso(Date fechaCreacionProceso) {
        this.fechaCreacionProceso = fechaCreacionProceso;
    }

    @Column(name = "activo")
    public Boolean getActivo() {
        return this.activo;
    }

    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "procesoRecaudacion")
    public Set<ServicioProcesoRecaudacion> getServicioProcesoRecaudacions() {
        return this.servicioProcesoRecaudacions;
    }

    public void setServicioProcesoRecaudacions(Set<ServicioProcesoRecaudacion> servicioProcesoRecaudacions) {
        this.servicioProcesoRecaudacions = servicioProcesoRecaudacions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "procesoRecaudacion")
    public Set<EgresoRecaudacion> getEgresoRecaudacions() {
        return this.egresoRecaudacions;
    }

    public void setEgresoRecaudacions(Set<EgresoRecaudacion> egresoRecaudacions) {
        this.egresoRecaudacions = egresoRecaudacions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "procesoRecaudacion")
    public Set<Guia> getGuias() {
        return this.guias;
    }

    public void setGuias(Set<Guia> guias) {
        this.guias = guias;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idProcesoRecaudacion != null ? idProcesoRecaudacion.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof ProcesoRecaudacion)) {
            return false;
        }
        ProcesoRecaudacion other = (ProcesoRecaudacion) object;
        if ((this.idProcesoRecaudacion == null && other.idProcesoRecaudacion != null) || (this.idProcesoRecaudacion != null && !this.idProcesoRecaudacion.equals(other.idProcesoRecaudacion))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return nombreProceso;
    }

}
