package com.areatecnica.sigf_v1.entities;
// Generated 25-01-2017 1:49:40 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReconocimientoDeuda generated by hbm2java
 */
@Entity
@Table(name="reconocimiento_deuda"
    ,catalog="sigf_v1"
)
public class ReconocimientoDeuda  implements java.io.Serializable {


     private Integer idReconocimientoDeuda;
     private Empresa empresa;
     private Trabajador trabajador;
     private int montoReconocimiento;
     private String descripcionReconocimiento;
     private Date fechaIngresoReconocimiento;
     private Date fechaActualizacionReconocimiento;

    public ReconocimientoDeuda() {
    }

	
    public ReconocimientoDeuda(Empresa empresa, Trabajador trabajador, int montoReconocimiento, Date fechaIngresoReconocimiento) {
        this.empresa = empresa;
        this.trabajador = trabajador;
        this.montoReconocimiento = montoReconocimiento;
        this.fechaIngresoReconocimiento = fechaIngresoReconocimiento;
    }
    public ReconocimientoDeuda(Empresa empresa, Trabajador trabajador, int montoReconocimiento, String descripcionReconocimiento, Date fechaIngresoReconocimiento, Date fechaActualizacionReconocimiento) {
       this.empresa = empresa;
       this.trabajador = trabajador;
       this.montoReconocimiento = montoReconocimiento;
       this.descripcionReconocimiento = descripcionReconocimiento;
       this.fechaIngresoReconocimiento = fechaIngresoReconocimiento;
       this.fechaActualizacionReconocimiento = fechaActualizacionReconocimiento;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_reconocimiento_deuda", unique=true, nullable=false)
    public Integer getIdReconocimientoDeuda() {
        return this.idReconocimientoDeuda;
    }
    
    public void setIdReconocimientoDeuda(Integer idReconocimientoDeuda) {
        this.idReconocimientoDeuda = idReconocimientoDeuda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_empresa", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_trabajador", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    
    @Column(name="monto_reconocimiento", nullable=false)
    public int getMontoReconocimiento() {
        return this.montoReconocimiento;
    }
    
    public void setMontoReconocimiento(int montoReconocimiento) {
        this.montoReconocimiento = montoReconocimiento;
    }

    
    @Column(name="descripcion_reconocimiento")
    public String getDescripcionReconocimiento() {
        return this.descripcionReconocimiento;
    }
    
    public void setDescripcionReconocimiento(String descripcionReconocimiento) {
        this.descripcionReconocimiento = descripcionReconocimiento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_ingreso_reconocimiento", nullable=false, length=10)
    public Date getFechaIngresoReconocimiento() {
        return this.fechaIngresoReconocimiento;
    }
    
    public void setFechaIngresoReconocimiento(Date fechaIngresoReconocimiento) {
        this.fechaIngresoReconocimiento = fechaIngresoReconocimiento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_actualizacion_reconocimiento", length=10)
    public Date getFechaActualizacionReconocimiento() {
        return this.fechaActualizacionReconocimiento;
    }
    
    public void setFechaActualizacionReconocimiento(Date fechaActualizacionReconocimiento) {
        this.fechaActualizacionReconocimiento = fechaActualizacionReconocimiento;
    }




}


