package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name="region"
    ,catalog="sigf_v1"
)
public class Region  implements java.io.Serializable {


     private Integer idRegion;
     private int numeroRegion;
     private String nombre;
     private Set<Comuna> comunas = new HashSet<Comuna>(0);
     private Set<UnidadNegocio> unidadNegocios = new HashSet<UnidadNegocio>(0);

    public Region() {
    }

	
    public Region(int numeroRegion, String nombre) {
        this.numeroRegion = numeroRegion;
        this.nombre = nombre;
    }
    public Region(int numeroRegion, String nombre, Set<Comuna> comunas, Set<UnidadNegocio> unidadNegocios) {
       this.numeroRegion = numeroRegion;
       this.nombre = nombre;
       this.comunas = comunas;
       this.unidadNegocios = unidadNegocios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_region", unique=true, nullable=false)
    public Integer getIdRegion() {
        return this.idRegion;
    }
    
    public void setIdRegion(Integer idRegion) {
        this.idRegion = idRegion;
    }

    
    @Column(name="numero_region", nullable=false)
    public int getNumeroRegion() {
        return this.numeroRegion;
    }
    
    public void setNumeroRegion(int numeroRegion) {
        this.numeroRegion = numeroRegion;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="region")
    public Set<Comuna> getComunas() {
        return this.comunas;
    }
    
    public void setComunas(Set<Comuna> comunas) {
        this.comunas = comunas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="region")
    public Set<UnidadNegocio> getUnidadNegocios() {
        return this.unidadNegocios;
    }
    
    public void setUnidadNegocios(Set<UnidadNegocio> unidadNegocios) {
        this.unidadNegocios = unidadNegocios;
    }




}


