package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RepresentanteLegal generated by hbm2java
 */
@Entity
@Table(name="representante_legal"
    ,catalog="sigf_v1"
)
public class RepresentanteLegal  implements java.io.Serializable {


     private Integer idRepresentanteLegal;
     private String nombreRepresentanteLegal;
     private String rutRepresentanteLegal;
     private String direccionRepresentanteLegal;
     private String telefonoRepresentanteLegal;
     private String emailRepresentanteLegal;
     private Set<RepresentanteEmpresa> representanteEmpresas = new HashSet<RepresentanteEmpresa>(0);

    public RepresentanteLegal() {
    }

	
    public RepresentanteLegal(String nombreRepresentanteLegal, String rutRepresentanteLegal) {
        this.nombreRepresentanteLegal = nombreRepresentanteLegal;
        this.rutRepresentanteLegal = rutRepresentanteLegal;
    }
    public RepresentanteLegal(String nombreRepresentanteLegal, String rutRepresentanteLegal, String direccionRepresentanteLegal, String telefonoRepresentanteLegal, String emailRepresentanteLegal, Set<RepresentanteEmpresa> representanteEmpresas) {
       this.nombreRepresentanteLegal = nombreRepresentanteLegal;
       this.rutRepresentanteLegal = rutRepresentanteLegal;
       this.direccionRepresentanteLegal = direccionRepresentanteLegal;
       this.telefonoRepresentanteLegal = telefonoRepresentanteLegal;
       this.emailRepresentanteLegal = emailRepresentanteLegal;
       this.representanteEmpresas = representanteEmpresas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_representante_legal", unique=true, nullable=false)
    public Integer getIdRepresentanteLegal() {
        return this.idRepresentanteLegal;
    }
    
    public void setIdRepresentanteLegal(Integer idRepresentanteLegal) {
        this.idRepresentanteLegal = idRepresentanteLegal;
    }

    
    @Column(name="nombre_representante_legal", nullable=false, length=45)
    public String getNombreRepresentanteLegal() {
        return this.nombreRepresentanteLegal;
    }
    
    public void setNombreRepresentanteLegal(String nombreRepresentanteLegal) {
        this.nombreRepresentanteLegal = nombreRepresentanteLegal;
    }

    
    @Column(name="rut_representante_legal", nullable=false, length=45)
    public String getRutRepresentanteLegal() {
        return this.rutRepresentanteLegal;
    }
    
    public void setRutRepresentanteLegal(String rutRepresentanteLegal) {
        this.rutRepresentanteLegal = rutRepresentanteLegal;
    }

    
    @Column(name="direccion_representante_legal", length=45)
    public String getDireccionRepresentanteLegal() {
        return this.direccionRepresentanteLegal;
    }
    
    public void setDireccionRepresentanteLegal(String direccionRepresentanteLegal) {
        this.direccionRepresentanteLegal = direccionRepresentanteLegal;
    }

    
    @Column(name="telefono_representante_legal", length=45)
    public String getTelefonoRepresentanteLegal() {
        return this.telefonoRepresentanteLegal;
    }
    
    public void setTelefonoRepresentanteLegal(String telefonoRepresentanteLegal) {
        this.telefonoRepresentanteLegal = telefonoRepresentanteLegal;
    }

    
    @Column(name="email_representante_legal", length=45)
    public String getEmailRepresentanteLegal() {
        return this.emailRepresentanteLegal;
    }
    
    public void setEmailRepresentanteLegal(String emailRepresentanteLegal) {
        this.emailRepresentanteLegal = emailRepresentanteLegal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="representanteLegal")
    public Set<RepresentanteEmpresa> getRepresentanteEmpresas() {
        return this.representanteEmpresas;
    }
    
    public void setRepresentanteEmpresas(Set<RepresentanteEmpresa> representanteEmpresas) {
        this.representanteEmpresas = representanteEmpresas;
    }




}


