package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RepresentanteEmpresa generated by hbm2java
 */
@Entity
@Table(name="representante_empresa"
    ,catalog="sigf_v1"
)
public class RepresentanteEmpresa  implements java.io.Serializable {


     private Integer idRepresentanteEmpresa;
     private Empresa empresa;
     private RepresentanteLegal representanteLegal;

    public RepresentanteEmpresa() {
    }

    public RepresentanteEmpresa(Empresa empresa, RepresentanteLegal representanteLegal) {
       this.empresa = empresa;
       this.representanteLegal = representanteLegal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_representante_empresa", unique=true, nullable=false)
    public Integer getIdRepresentanteEmpresa() {
        return this.idRepresentanteEmpresa;
    }
    
    public void setIdRepresentanteEmpresa(Integer idRepresentanteEmpresa) {
        this.idRepresentanteEmpresa = idRepresentanteEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_empresa", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_representante_legal", nullable=false)
    public RepresentanteLegal getRepresentanteLegal() {
        return this.representanteLegal;
    }
    
    public void setRepresentanteLegal(RepresentanteLegal representanteLegal) {
        this.representanteLegal = representanteLegal;
    }




}


