package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", catalog = "sigf_v1"
)
public class Rol implements java.io.Serializable {

    private Integer idRol;
    private String nombreRol;
    private String descripcion;
    private Set<Usuario> usuarios = new HashSet<Usuario>(0);
    private Set<RolPrivilegio> rolPrivilegios = new HashSet<RolPrivilegio>(0);

    public Rol() {
    }

    public Rol(String nombreRol, String descripcion) {
        this.nombreRol = nombreRol;
        this.descripcion = descripcion;
    }

    public Rol(String nombreRol, String descripcion, Set<Usuario> usuarios, Set<RolPrivilegio> rolPrivilegios) {
        this.nombreRol = nombreRol;
        this.descripcion = descripcion;
        this.usuarios = usuarios;
        this.rolPrivilegios = rolPrivilegios;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_rol", unique = true, nullable = false)
    public Integer getIdRol() {
        return this.idRol;
    }

    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }

    @Column(name = "nombre_rol", nullable = false)
    public String getNombreRol() {
        return this.nombreRol;
    }

    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }

    @Column(name = "descripcion", nullable = false)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
    public Set<RolPrivilegio> getRolPrivilegios() {
        return this.rolPrivilegios;
    }

    public void setRolPrivilegios(Set<RolPrivilegio> rolPrivilegios) {
        this.rolPrivilegios = rolPrivilegios;
    }

}
