package com.areatecnica.sigf_v1.entities;
// Generated 26-01-2017 15:49:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolPrivilegio generated by hbm2java
 */
@Entity
@Table(name="rol_privilegio"
    ,catalog="sigf_v1"
)
public class RolPrivilegio  implements java.io.Serializable {


     private Integer idRolPrivilegio;
     private Privilegio privilegio;
     private Rol rol;

    public RolPrivilegio() {
    }

    public RolPrivilegio(Privilegio privilegio, Rol rol) {
       this.privilegio = privilegio;
       this.rol = rol;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_rol_privilegio", unique=true, nullable=false)
    public Integer getIdRolPrivilegio() {
        return this.idRolPrivilegio;
    }
    
    public void setIdRolPrivilegio(Integer idRolPrivilegio) {
        this.idRolPrivilegio = idRolPrivilegio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_privilegio", nullable=false)
    public Privilegio getPrivilegio() {
        return this.privilegio;
    }
    
    public void setPrivilegio(Privilegio privilegio) {
        this.privilegio = privilegio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_rol", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }




}


