package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Server generated by hbm2java
 */
@Entity
@Table(name="server"
    ,catalog="sigf_v1"
)
public class Server  implements java.io.Serializable {


     private Integer id;
     private boolean registration;
     private String map;
     private String bingKey;
     private String mapUrl;
     private String language;
     private String distanceUnit;
     private String speedUnit;
     private double latitude;
     private double longitude;
     private int zoom;

    public Server() {
    }

	
    public Server(boolean registration, double latitude, double longitude, int zoom) {
        this.registration = registration;
        this.latitude = latitude;
        this.longitude = longitude;
        this.zoom = zoom;
    }
    public Server(boolean registration, String map, String bingKey, String mapUrl, String language, String distanceUnit, String speedUnit, double latitude, double longitude, int zoom) {
       this.registration = registration;
       this.map = map;
       this.bingKey = bingKey;
       this.mapUrl = mapUrl;
       this.language = language;
       this.distanceUnit = distanceUnit;
       this.speedUnit = speedUnit;
       this.latitude = latitude;
       this.longitude = longitude;
       this.zoom = zoom;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="registration", nullable=false)
    public boolean isRegistration() {
        return this.registration;
    }
    
    public void setRegistration(boolean registration) {
        this.registration = registration;
    }

    
    @Column(name="map", length=128)
    public String getMap() {
        return this.map;
    }
    
    public void setMap(String map) {
        this.map = map;
    }

    
    @Column(name="bingKey", length=128)
    public String getBingKey() {
        return this.bingKey;
    }
    
    public void setBingKey(String bingKey) {
        this.bingKey = bingKey;
    }

    
    @Column(name="mapUrl", length=128)
    public String getMapUrl() {
        return this.mapUrl;
    }
    
    public void setMapUrl(String mapUrl) {
        this.mapUrl = mapUrl;
    }

    
    @Column(name="language", length=128)
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }

    
    @Column(name="distanceUnit", length=128)
    public String getDistanceUnit() {
        return this.distanceUnit;
    }
    
    public void setDistanceUnit(String distanceUnit) {
        this.distanceUnit = distanceUnit;
    }

    
    @Column(name="speedUnit", length=128)
    public String getSpeedUnit() {
        return this.speedUnit;
    }
    
    public void setSpeedUnit(String speedUnit) {
        this.speedUnit = speedUnit;
    }

    
    @Column(name="latitude", nullable=false, precision=22, scale=0)
    public double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="longitude", nullable=false, precision=22, scale=0)
    public double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="zoom", nullable=false)
    public int getZoom() {
        return this.zoom;
    }
    
    public void setZoom(int zoom) {
        this.zoom = zoom;
    }




}


