package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ServicioProcesoRecaudacion generated by hbm2java
 */
@Entity
@Table(name="servicio_proceso_recaudacion"
    ,catalog="sigf_v1"
)
public class ServicioProcesoRecaudacion  implements java.io.Serializable {


     private int idServicioProcesoRecaudacion;
     private ProcesoRecaudacion procesoRecaudacion;
     private Servicio servicio;

    public ServicioProcesoRecaudacion() {
    }

    public ServicioProcesoRecaudacion(int idServicioProcesoRecaudacion, ProcesoRecaudacion procesoRecaudacion, Servicio servicio) {
       this.idServicioProcesoRecaudacion = idServicioProcesoRecaudacion;
       this.procesoRecaudacion = procesoRecaudacion;
       this.servicio = servicio;
    }
   
     @Id 

    
    @Column(name="id_servicio_proceso_recaudacion", unique=true, nullable=false)
    public int getIdServicioProcesoRecaudacion() {
        return this.idServicioProcesoRecaudacion;
    }
    
    public void setIdServicioProcesoRecaudacion(int idServicioProcesoRecaudacion) {
        this.idServicioProcesoRecaudacion = idServicioProcesoRecaudacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_proceso_recaudacion", nullable=false)
    public ProcesoRecaudacion getProcesoRecaudacion() {
        return this.procesoRecaudacion;
    }
    
    public void setProcesoRecaudacion(ProcesoRecaudacion procesoRecaudacion) {
        this.procesoRecaudacion = procesoRecaudacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_servicio", nullable=false)
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }




}


