package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SindicatoTrabajador generated by hbm2java
 */
@Entity
@Table(name="sindicato_trabajador"
    ,catalog="sigf_v1"
)
public class SindicatoTrabajador  implements java.io.Serializable {


     private Integer idSindicatoTrabajador;
     private Sindicato sindicato;
     private Trabajador trabajador;
     private Date fechaIngreso;
     private Set<MontoSindicatoTrabajador> montoSindicatoTrabajadors = new HashSet<MontoSindicatoTrabajador>(0);

    public SindicatoTrabajador() {
    }

	
    public SindicatoTrabajador(Sindicato sindicato, Trabajador trabajador, Date fechaIngreso) {
        this.sindicato = sindicato;
        this.trabajador = trabajador;
        this.fechaIngreso = fechaIngreso;
    }
    public SindicatoTrabajador(Sindicato sindicato, Trabajador trabajador, Date fechaIngreso, Set<MontoSindicatoTrabajador> montoSindicatoTrabajadors) {
       this.sindicato = sindicato;
       this.trabajador = trabajador;
       this.fechaIngreso = fechaIngreso;
       this.montoSindicatoTrabajadors = montoSindicatoTrabajadors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_sindicato_trabajador", unique=true, nullable=false)
    public Integer getIdSindicatoTrabajador() {
        return this.idSindicatoTrabajador;
    }
    
    public void setIdSindicatoTrabajador(Integer idSindicatoTrabajador) {
        this.idSindicatoTrabajador = idSindicatoTrabajador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sindicato", nullable=false)
    public Sindicato getSindicato() {
        return this.sindicato;
    }
    
    public void setSindicato(Sindicato sindicato) {
        this.sindicato = sindicato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_trabajador", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_ingreso", nullable=false, length=19)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sindicatoTrabajador")
    public Set<MontoSindicatoTrabajador> getMontoSindicatoTrabajadors() {
        return this.montoSindicatoTrabajadors;
    }
    
    public void setMontoSindicatoTrabajadors(Set<MontoSindicatoTrabajador> montoSindicatoTrabajadors) {
        this.montoSindicatoTrabajadors = montoSindicatoTrabajadors;
    }




}


