package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TarifaServicio generated by hbm2java
 */
@Entity
@Table(name="tarifa_servicio"
    ,catalog="sigf_v1"
)
public class TarifaServicio  implements java.io.Serializable {


     private Integer idTarifaServicio;
     private Boleto boleto;
     private Servicio servicio;
     private int valorTarifa;
     private int mes;
     private int anio;
     private boolean activa;

    public TarifaServicio() {
    }

    public TarifaServicio(Boleto boleto, Servicio servicio, int valorTarifa, int mes, int anio, boolean activa) {
       this.boleto = boleto;
       this.servicio = servicio;
       this.valorTarifa = valorTarifa;
       this.mes = mes;
       this.anio = anio;
       this.activa = activa;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tarifa_servicio", unique=true, nullable=false)
    public Integer getIdTarifaServicio() {
        return this.idTarifaServicio;
    }
    
    public void setIdTarifaServicio(Integer idTarifaServicio) {
        this.idTarifaServicio = idTarifaServicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_boleto", nullable=false)
    public Boleto getBoleto() {
        return this.boleto;
    }
    
    public void setBoleto(Boleto boleto) {
        this.boleto = boleto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_servicio", nullable=false)
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }

    
    @Column(name="valor_tarifa", nullable=false)
    public int getValorTarifa() {
        return this.valorTarifa;
    }
    
    public void setValorTarifa(int valorTarifa) {
        this.valorTarifa = valorTarifa;
    }

    
    @Column(name="mes", nullable=false)
    public int getMes() {
        return this.mes;
    }
    
    public void setMes(int mes) {
        this.mes = mes;
    }

    
    @Column(name="anio", nullable=false)
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }

    
    @Column(name="activa", nullable=false)
    public boolean isActiva() {
        return this.activa;
    }
    
    public void setActiva(boolean activa) {
        this.activa = activa;
    }




}


