package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoCargo generated by hbm2java
 */
@Entity
@Table(name="tipo_cargo"
    ,catalog="sigf_v1"
)
public class TipoCargo  implements java.io.Serializable {


     private Integer idTipoCargo;
     private String nombreTipoCargo;
     private Date fechaIngreso;
     private Integer montoDefecto;
     private Set<CargoBus> cargoBuses = new HashSet<CargoBus>(0);

    public TipoCargo() {
    }

	
    public TipoCargo(String nombreTipoCargo, Date fechaIngreso) {
        this.nombreTipoCargo = nombreTipoCargo;
        this.fechaIngreso = fechaIngreso;
    }
    public TipoCargo(String nombreTipoCargo, Date fechaIngreso, Integer montoDefecto, Set<CargoBus> cargoBuses) {
       this.nombreTipoCargo = nombreTipoCargo;
       this.fechaIngreso = fechaIngreso;
       this.montoDefecto = montoDefecto;
       this.cargoBuses = cargoBuses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_cargo", unique=true, nullable=false)
    public Integer getIdTipoCargo() {
        return this.idTipoCargo;
    }
    
    public void setIdTipoCargo(Integer idTipoCargo) {
        this.idTipoCargo = idTipoCargo;
    }

    
    @Column(name="nombre_tipo_cargo", nullable=false, length=45)
    public String getNombreTipoCargo() {
        return this.nombreTipoCargo;
    }
    
    public void setNombreTipoCargo(String nombreTipoCargo) {
        this.nombreTipoCargo = nombreTipoCargo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_ingreso", nullable=false, length=19)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="monto_defecto")
    public Integer getMontoDefecto() {
        return this.montoDefecto;
    }
    
    public void setMontoDefecto(Integer montoDefecto) {
        this.montoDefecto = montoDefecto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoCargo")
    public Set<CargoBus> getCargoBuses() {
        return this.cargoBuses;
    }
    
    public void setCargoBuses(Set<CargoBus> cargoBuses) {
        this.cargoBuses = cargoBuses;
    }




}


