package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoCotizacionTrabajador generated by hbm2java
 */
@Entity
@Table(name="tipo_cotizacion_trabajador"
    ,catalog="sigf_v1"
)
public class TipoCotizacionTrabajador  implements java.io.Serializable {


     private Integer idTipoCotizacionTrabajador;
     private String nombreTipoCotizacionTrabajador;
     private Set<Trabajador> trabajadors = new HashSet<Trabajador>(0);

    public TipoCotizacionTrabajador() {
    }

    public TipoCotizacionTrabajador(String nombreTipoCotizacionTrabajador, Set<Trabajador> trabajadors) {
       this.nombreTipoCotizacionTrabajador = nombreTipoCotizacionTrabajador;
       this.trabajadors = trabajadors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_cotizacion_trabajador", unique=true, nullable=false)
    public Integer getIdTipoCotizacionTrabajador() {
        return this.idTipoCotizacionTrabajador;
    }
    
    public void setIdTipoCotizacionTrabajador(Integer idTipoCotizacionTrabajador) {
        this.idTipoCotizacionTrabajador = idTipoCotizacionTrabajador;
    }

    
    @Column(name="nombre_tipo_cotizacion_trabajador", length=100)
    public String getNombreTipoCotizacionTrabajador() {
        return this.nombreTipoCotizacionTrabajador;
    }
    
    public void setNombreTipoCotizacionTrabajador(String nombreTipoCotizacionTrabajador) {
        this.nombreTipoCotizacionTrabajador = nombreTipoCotizacionTrabajador;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoCotizacionTrabajador")
    public Set<Trabajador> getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set<Trabajador> trabajadors) {
        this.trabajadors = trabajadors;
    }




}


