package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoInstitucionApv generated by hbm2java
 */
@Entity
@Table(name="tipo_institucion_apv"
    ,catalog="sigf_v1"
)
public class TipoInstitucionApv  implements java.io.Serializable {


     private Integer idTipoInstitucionApv;
     private String nombreTipoApv;
     private Set<InstitucionApv> institucionApvs = new HashSet<InstitucionApv>(0);

    public TipoInstitucionApv() {
    }

	
    public TipoInstitucionApv(String nombreTipoApv) {
        this.nombreTipoApv = nombreTipoApv;
    }
    public TipoInstitucionApv(String nombreTipoApv, Set<InstitucionApv> institucionApvs) {
       this.nombreTipoApv = nombreTipoApv;
       this.institucionApvs = institucionApvs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_institucion_apv", unique=true, nullable=false)
    public Integer getIdTipoInstitucionApv() {
        return this.idTipoInstitucionApv;
    }
    
    public void setIdTipoInstitucionApv(Integer idTipoInstitucionApv) {
        this.idTipoInstitucionApv = idTipoInstitucionApv;
    }

    
    @Column(name="nombre_tipo_apv", nullable=false, length=100)
    public String getNombreTipoApv() {
        return this.nombreTipoApv;
    }
    
    public void setNombreTipoApv(String nombreTipoApv) {
        this.nombreTipoApv = nombreTipoApv;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoInstitucionApv")
    public Set<InstitucionApv> getInstitucionApvs() {
        return this.institucionApvs;
    }
    
    public void setInstitucionApvs(Set<InstitucionApv> institucionApvs) {
        this.institucionApvs = institucionApvs;
    }




}


