package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoTrabajador generated by hbm2java
 */
@Entity
@Table(name = "tipo_trabajador", catalog = "sigf_v1"
)
public class TipoTrabajador implements java.io.Serializable {

    private Integer idTipoTrabajador;
    private String nombreTipoTrabajador;
    private Set<RelacionLaboral> relacionLaborals = new HashSet<RelacionLaboral>(0);

    public TipoTrabajador() {
    }

    public TipoTrabajador(String nombreTipoTrabajador) {
        this.nombreTipoTrabajador = nombreTipoTrabajador;
    }

    public TipoTrabajador(String nombreTipoTrabajador, Set<RelacionLaboral> relacionLaborals) {
        this.nombreTipoTrabajador = nombreTipoTrabajador;
        this.relacionLaborals = relacionLaborals;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_tipo_trabajador", unique = true, nullable = false)
    public Integer getIdTipoTrabajador() {
        return this.idTipoTrabajador;
    }

    public void setIdTipoTrabajador(Integer idTipoTrabajador) {
        this.idTipoTrabajador = idTipoTrabajador;
    }

    @Column(name = "nombre_tipo_trabajador", nullable = false, length = 45)
    public String getNombreTipoTrabajador() {
        return this.nombreTipoTrabajador;
    }

    public void setNombreTipoTrabajador(String nombreTipoTrabajador) {
        this.nombreTipoTrabajador = nombreTipoTrabajador;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoTrabajador")
    public Set<RelacionLaboral> getRelacionLaborals() {
        return this.relacionLaborals;
    }

    public void setRelacionLaborals(Set<RelacionLaboral> relacionLaborals) {
        this.relacionLaborals = relacionLaborals;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idTipoTrabajador != null ? idTipoTrabajador.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof TipoTrabajador)) {
            return false;
        }
        TipoTrabajador other = (TipoTrabajador) object;
        if ((this.idTipoTrabajador == null && other.idTipoTrabajador != null) || (this.idTipoTrabajador != null && !this.idTipoTrabajador.equals(other.idTipoTrabajador))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return nombreTipoTrabajador;
    }

}
