package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoAbono generated by hbm2java
 */
@Entity
@Table(name="tipo_abono"
    ,catalog="sigf_v1"
)
public class TipoAbono  implements java.io.Serializable {


     private Integer idTipoAbono;
     private String nombreTipoAbono;
     private Date fechaIngreso;
     private Integer montoDefecto;
     private Set<AbonoBus> abonoBuses = new HashSet<AbonoBus>(0);

    public TipoAbono() {
    }

	
    public TipoAbono(String nombreTipoAbono, Date fechaIngreso) {
        this.nombreTipoAbono = nombreTipoAbono;
        this.fechaIngreso = fechaIngreso;
    }
    public TipoAbono(String nombreTipoAbono, Date fechaIngreso, Integer montoDefecto, Set<AbonoBus> abonoBuses) {
       this.nombreTipoAbono = nombreTipoAbono;
       this.fechaIngreso = fechaIngreso;
       this.montoDefecto = montoDefecto;
       this.abonoBuses = abonoBuses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_abono", unique=true, nullable=false)
    public Integer getIdTipoAbono() {
        return this.idTipoAbono;
    }
    
    public void setIdTipoAbono(Integer idTipoAbono) {
        this.idTipoAbono = idTipoAbono;
    }

    
    @Column(name="nombre_tipo_abono", nullable=false, length=45)
    public String getNombreTipoAbono() {
        return this.nombreTipoAbono;
    }
    
    public void setNombreTipoAbono(String nombreTipoAbono) {
        this.nombreTipoAbono = nombreTipoAbono;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_ingreso", nullable=false, length=19)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="monto_defecto")
    public Integer getMontoDefecto() {
        return this.montoDefecto;
    }
    
    public void setMontoDefecto(Integer montoDefecto) {
        this.montoDefecto = montoDefecto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoAbono")
    public Set<AbonoBus> getAbonoBuses() {
        return this.abonoBuses;
    }
    
    public void setAbonoBuses(Set<AbonoBus> abonoBuses) {
        this.abonoBuses = abonoBuses;
    }




}


