package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoCuentaBanco generated by hbm2java
 */
@Entity
@Table(name="tipo_cuenta_banco"
    ,catalog="sigf_v1"
)
public class TipoCuentaBanco  implements java.io.Serializable {


     private Integer idTipoCuentaBanco;
     private String nombreTipoCuenta;
     private Set<CuentaBancariaTrabajador> cuentaBancariaTrabajadors = new HashSet<CuentaBancariaTrabajador>(0);
     private Set<CuentaBancariaEmpresa> cuentaBancariaEmpresas = new HashSet<CuentaBancariaEmpresa>(0);

    public TipoCuentaBanco() {
    }

	
    public TipoCuentaBanco(String nombreTipoCuenta) {
        this.nombreTipoCuenta = nombreTipoCuenta;
    }
    public TipoCuentaBanco(String nombreTipoCuenta, Set<CuentaBancariaTrabajador> cuentaBancariaTrabajadors, Set<CuentaBancariaEmpresa> cuentaBancariaEmpresas) {
       this.nombreTipoCuenta = nombreTipoCuenta;
       this.cuentaBancariaTrabajadors = cuentaBancariaTrabajadors;
       this.cuentaBancariaEmpresas = cuentaBancariaEmpresas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_cuenta_banco", unique=true, nullable=false)
    public Integer getIdTipoCuentaBanco() {
        return this.idTipoCuentaBanco;
    }
    
    public void setIdTipoCuentaBanco(Integer idTipoCuentaBanco) {
        this.idTipoCuentaBanco = idTipoCuentaBanco;
    }

    
    @Column(name="nombre_tipo_cuenta", nullable=false, length=45)
    public String getNombreTipoCuenta() {
        return this.nombreTipoCuenta;
    }
    
    public void setNombreTipoCuenta(String nombreTipoCuenta) {
        this.nombreTipoCuenta = nombreTipoCuenta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoCuentaBanco")
    public Set<CuentaBancariaTrabajador> getCuentaBancariaTrabajadors() {
        return this.cuentaBancariaTrabajadors;
    }
    
    public void setCuentaBancariaTrabajadors(Set<CuentaBancariaTrabajador> cuentaBancariaTrabajadors) {
        this.cuentaBancariaTrabajadors = cuentaBancariaTrabajadors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoCuentaBanco")
    public Set<CuentaBancariaEmpresa> getCuentaBancariaEmpresas() {
        return this.cuentaBancariaEmpresas;
    }
    
    public void setCuentaBancariaEmpresas(Set<CuentaBancariaEmpresa> cuentaBancariaEmpresas) {
        this.cuentaBancariaEmpresas = cuentaBancariaEmpresas;
    }




}


