package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoCarga generated by hbm2java
 */
@Entity
@Table(name="tipo_carga"
    ,catalog="sigf_v1"
)
public class TipoCarga  implements java.io.Serializable {


     private Integer idTipoCarga;
     private String nombreTipoCarga;
     private Set<CargasTrabajador> cargasTrabajadors = new HashSet<CargasTrabajador>(0);

    public TipoCarga() {
    }

	
    public TipoCarga(String nombreTipoCarga) {
        this.nombreTipoCarga = nombreTipoCarga;
    }
    public TipoCarga(String nombreTipoCarga, Set<CargasTrabajador> cargasTrabajadors) {
       this.nombreTipoCarga = nombreTipoCarga;
       this.cargasTrabajadors = cargasTrabajadors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_carga", unique=true, nullable=false)
    public Integer getIdTipoCarga() {
        return this.idTipoCarga;
    }
    
    public void setIdTipoCarga(Integer idTipoCarga) {
        this.idTipoCarga = idTipoCarga;
    }

    
    @Column(name="nombre_tipo_carga", nullable=false, length=45)
    public String getNombreTipoCarga() {
        return this.nombreTipoCarga;
    }
    
    public void setNombreTipoCarga(String nombreTipoCarga) {
        this.nombreTipoCarga = nombreTipoCarga;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoCarga")
    public Set<CargasTrabajador> getCargasTrabajadors() {
        return this.cargasTrabajadors;
    }
    
    public void setCargasTrabajadors(Set<CargasTrabajador> cargasTrabajadors) {
        this.cargasTrabajadors = cargasTrabajadors;
    }




}


