package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoMovimientoPersonal generated by hbm2java
 */
@Entity
@Table(name="tipo_movimiento_personal"
    ,catalog="sigf_v1"
)
public class TipoMovimientoPersonal  implements java.io.Serializable {


     private Integer idTipoMovimientoPersonal;
     private String nombreTipoMovtoPersonal;

    public TipoMovimientoPersonal() {
    }

    public TipoMovimientoPersonal(String nombreTipoMovtoPersonal) {
       this.nombreTipoMovtoPersonal = nombreTipoMovtoPersonal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_movimiento_personal", unique=true, nullable=false)
    public Integer getIdTipoMovimientoPersonal() {
        return this.idTipoMovimientoPersonal;
    }
    
    public void setIdTipoMovimientoPersonal(Integer idTipoMovimientoPersonal) {
        this.idTipoMovimientoPersonal = idTipoMovimientoPersonal;
    }

    
    @Column(name="nombre_tipo_movto_personal", nullable=false, length=100)
    public String getNombreTipoMovtoPersonal() {
        return this.nombreTipoMovtoPersonal;
    }
    
    public void setNombreTipoMovtoPersonal(String nombreTipoMovtoPersonal) {
        this.nombreTipoMovtoPersonal = nombreTipoMovtoPersonal;
    }




}


