package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoControl generated by hbm2java
 */
@Entity
@Table(name="tipo_control"
    ,catalog="sigf_v1"
)
public class TipoControl  implements java.io.Serializable {


     private Integer idTipoControl;
     private String nombreTipoControl;
     private String clasificacion;
     private Set<Control> controls = new HashSet<Control>(0);

    public TipoControl() {
    }

	
    public TipoControl(String nombreTipoControl) {
        this.nombreTipoControl = nombreTipoControl;
    }
    public TipoControl(String nombreTipoControl, String clasificacion, Set<Control> controls) {
       this.nombreTipoControl = nombreTipoControl;
       this.clasificacion = clasificacion;
       this.controls = controls;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_control", unique=true, nullable=false)
    public Integer getIdTipoControl() {
        return this.idTipoControl;
    }
    
    public void setIdTipoControl(Integer idTipoControl) {
        this.idTipoControl = idTipoControl;
    }

    
    @Column(name="nombre_tipo_control", nullable=false, length=45)
    public String getNombreTipoControl() {
        return this.nombreTipoControl;
    }
    
    public void setNombreTipoControl(String nombreTipoControl) {
        this.nombreTipoControl = nombreTipoControl;
    }

    
    @Column(name="clasificacion", length=45)
    public String getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoControl")
    public Set<Control> getControls() {
        return this.controls;
    }
    
    public void setControls(Set<Control> controls) {
        this.controls = controls;
    }




}


