package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tope generated by hbm2java
 */
@Entity
@Table(name="tope"
    ,catalog="sigf_v1"
)
public class Tope  implements java.io.Serializable {


     private Integer idTope;
     private String nombreTope;
     private BigDecimal montoUf;

    public Tope() {
    }

    public Tope(String nombreTope, BigDecimal montoUf) {
       this.nombreTope = nombreTope;
       this.montoUf = montoUf;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tope", unique=true, nullable=false)
    public Integer getIdTope() {
        return this.idTope;
    }
    
    public void setIdTope(Integer idTope) {
        this.idTope = idTope;
    }

    
    @Column(name="nombre_tope", nullable=false)
    public String getNombreTope() {
        return this.nombreTope;
    }
    
    public void setNombreTope(String nombreTope) {
        this.nombreTope = nombreTope;
    }

    
    @Column(name="monto_uf", nullable=false, precision=10)
    public BigDecimal getMontoUf() {
        return this.montoUf;
    }
    
    public void setMontoUf(BigDecimal montoUf) {
        this.montoUf = montoUf;
    }




}


