package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TrabajadorTerminal generated by hbm2java
 */
@Entity
@Table(name="trabajador_terminal"
    ,catalog="sigf_v1"
)
public class TrabajadorTerminal  implements java.io.Serializable {


     private Integer idTrabajadorTerminal;
     private Terminal terminal;
     private Trabajador trabajador;

    public TrabajadorTerminal() {
    }

    public TrabajadorTerminal(Terminal terminal, Trabajador trabajador) {
       this.terminal = terminal;
       this.trabajador = trabajador;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_trabajador_terminal", unique=true, nullable=false)
    public Integer getIdTrabajadorTerminal() {
        return this.idTrabajadorTerminal;
    }
    
    public void setIdTrabajadorTerminal(Integer idTrabajadorTerminal) {
        this.idTrabajadorTerminal = idTrabajadorTerminal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_terminal", nullable=false)
    public Terminal getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(Terminal terminal) {
        this.terminal = terminal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_trabajador", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }




}


