package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnidadNegocio generated by hbm2java
 */
@Entity
@Table(name="unidad_negocio"
    ,catalog="sigf_v1"
)
public class UnidadNegocio  implements java.io.Serializable {


     private Integer idUnidadNegocio;
     private OperadorTransporte operadorTransporte;
     private Region region;
     private int numeroUnidadNegocio;
     private String nombreUnidadNegocio;
     private String folioUnidadNegocio;
     private Set<ContratoUnidad> contratoUnidads = new HashSet<ContratoUnidad>(0);
     private Set<Servicio> servicios = new HashSet<Servicio>(0);
     private Set<ValorRolloUnidad> valorRolloUnidads = new HashSet<ValorRolloUnidad>(0);
     private Set<Bus> buses = new HashSet<Bus>(0);

    public UnidadNegocio() {
    }

	
    public UnidadNegocio(OperadorTransporte operadorTransporte, Region region, int numeroUnidadNegocio, String nombreUnidadNegocio) {
        this.operadorTransporte = operadorTransporte;
        this.region = region;
        this.numeroUnidadNegocio = numeroUnidadNegocio;
        this.nombreUnidadNegocio = nombreUnidadNegocio;
    }
    public UnidadNegocio(OperadorTransporte operadorTransporte, Region region, int numeroUnidadNegocio, String nombreUnidadNegocio, String folioUnidadNegocio, Set<ContratoUnidad> contratoUnidads, Set<Servicio> servicios, Set<ValorRolloUnidad> valorRolloUnidads, Set<Bus> buses) {
       this.operadorTransporte = operadorTransporte;
       this.region = region;
       this.numeroUnidadNegocio = numeroUnidadNegocio;
       this.nombreUnidadNegocio = nombreUnidadNegocio;
       this.folioUnidadNegocio = folioUnidadNegocio;
       this.contratoUnidads = contratoUnidads;
       this.servicios = servicios;
       this.valorRolloUnidads = valorRolloUnidads;
       this.buses = buses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_unidad_negocio", unique=true, nullable=false)
    public Integer getIdUnidadNegocio() {
        return this.idUnidadNegocio;
    }
    
    public void setIdUnidadNegocio(Integer idUnidadNegocio) {
        this.idUnidadNegocio = idUnidadNegocio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_operador_transporte", nullable=false)
    public OperadorTransporte getOperadorTransporte() {
        return this.operadorTransporte;
    }
    
    public void setOperadorTransporte(OperadorTransporte operadorTransporte) {
        this.operadorTransporte = operadorTransporte;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_region", nullable=false)
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }

    
    @Column(name="numero_unidad_negocio", nullable=false)
    public int getNumeroUnidadNegocio() {
        return this.numeroUnidadNegocio;
    }
    
    public void setNumeroUnidadNegocio(int numeroUnidadNegocio) {
        this.numeroUnidadNegocio = numeroUnidadNegocio;
    }

    
    @Column(name="nombre_unidad_negocio", nullable=false, length=45)
    public String getNombreUnidadNegocio() {
        return this.nombreUnidadNegocio;
    }
    
    public void setNombreUnidadNegocio(String nombreUnidadNegocio) {
        this.nombreUnidadNegocio = nombreUnidadNegocio;
    }

    
    @Column(name="folio_unidad_negocio", length=45)
    public String getFolioUnidadNegocio() {
        return this.folioUnidadNegocio;
    }
    
    public void setFolioUnidadNegocio(String folioUnidadNegocio) {
        this.folioUnidadNegocio = folioUnidadNegocio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidadNegocio")
    public Set<ContratoUnidad> getContratoUnidads() {
        return this.contratoUnidads;
    }
    
    public void setContratoUnidads(Set<ContratoUnidad> contratoUnidads) {
        this.contratoUnidads = contratoUnidads;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidadNegocio")
    public Set<Servicio> getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set<Servicio> servicios) {
        this.servicios = servicios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidadNegocio")
    public Set<ValorRolloUnidad> getValorRolloUnidads() {
        return this.valorRolloUnidads;
    }
    
    public void setValorRolloUnidads(Set<ValorRolloUnidad> valorRolloUnidads) {
        this.valorRolloUnidads = valorRolloUnidads;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidadNegocio")
    public Set<Bus> getBuses() {
        return this.buses;
    }
    
    public void setBuses(Set<Bus> buses) {
        this.buses = buses;
    }




}


