package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="sigf_v1"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String hashedPassword;
     private String salt;
     private boolean readonly;
     private boolean admin;
     private String map;
     private String language;
     private String distanceUnit;
     private String speedUnit;
     private double latitude;
     private double longitude;
     private int zoom;
     private Set<UserDevice> userDevices = new HashSet<UserDevice>(0);

    public User() {
    }

	
    public User(String name, String email, String hashedPassword, String salt, boolean readonly, boolean admin, double latitude, double longitude, int zoom) {
        this.name = name;
        this.email = email;
        this.hashedPassword = hashedPassword;
        this.salt = salt;
        this.readonly = readonly;
        this.admin = admin;
        this.latitude = latitude;
        this.longitude = longitude;
        this.zoom = zoom;
    }
    public User(String name, String email, String hashedPassword, String salt, boolean readonly, boolean admin, String map, String language, String distanceUnit, String speedUnit, double latitude, double longitude, int zoom, Set<UserDevice> userDevices) {
       this.name = name;
       this.email = email;
       this.hashedPassword = hashedPassword;
       this.salt = salt;
       this.readonly = readonly;
       this.admin = admin;
       this.map = map;
       this.language = language;
       this.distanceUnit = distanceUnit;
       this.speedUnit = speedUnit;
       this.latitude = latitude;
       this.longitude = longitude;
       this.zoom = zoom;
       this.userDevices = userDevices;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=128)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", unique=true, nullable=false, length=128)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="hashedPassword", nullable=false, length=128)
    public String getHashedPassword() {
        return this.hashedPassword;
    }
    
    public void setHashedPassword(String hashedPassword) {
        this.hashedPassword = hashedPassword;
    }

    
    @Column(name="salt", nullable=false, length=128)
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }

    
    @Column(name="readonly", nullable=false)
    public boolean isReadonly() {
        return this.readonly;
    }
    
    public void setReadonly(boolean readonly) {
        this.readonly = readonly;
    }

    
    @Column(name="admin", nullable=false)
    public boolean isAdmin() {
        return this.admin;
    }
    
    public void setAdmin(boolean admin) {
        this.admin = admin;
    }

    
    @Column(name="map", length=128)
    public String getMap() {
        return this.map;
    }
    
    public void setMap(String map) {
        this.map = map;
    }

    
    @Column(name="language", length=128)
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }

    
    @Column(name="distanceUnit", length=128)
    public String getDistanceUnit() {
        return this.distanceUnit;
    }
    
    public void setDistanceUnit(String distanceUnit) {
        this.distanceUnit = distanceUnit;
    }

    
    @Column(name="speedUnit", length=128)
    public String getSpeedUnit() {
        return this.speedUnit;
    }
    
    public void setSpeedUnit(String speedUnit) {
        this.speedUnit = speedUnit;
    }

    
    @Column(name="latitude", nullable=false, precision=22, scale=0)
    public double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="longitude", nullable=false, precision=22, scale=0)
    public double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="zoom", nullable=false)
    public int getZoom() {
        return this.zoom;
    }
    
    public void setZoom(int zoom) {
        this.zoom = zoom;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<UserDevice> getUserDevices() {
        return this.userDevices;
    }
    
    public void setUserDevices(Set<UserDevice> userDevices) {
        this.userDevices = userDevices;
    }




}


