package com.areatecnica.sigf_v1.entities;
// Generated 28-08-2016 23:51:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ValorFijo generated by hbm2java
 */
@Entity
@Table(name="valor_fijo"
    ,catalog="sigf_v1"
)
public class ValorFijo  implements java.io.Serializable {


     private Integer idValorFijo;
     private String nombreValor;
     private BigDecimal monto;

    public ValorFijo() {
    }

	
    public ValorFijo(String nombreValor) {
        this.nombreValor = nombreValor;
    }
    public ValorFijo(String nombreValor, BigDecimal monto) {
       this.nombreValor = nombreValor;
       this.monto = monto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_valor_fijo", unique=true, nullable=false)
    public Integer getIdValorFijo() {
        return this.idValorFijo;
    }
    
    public void setIdValorFijo(Integer idValorFijo) {
        this.idValorFijo = idValorFijo;
    }

    
    @Column(name="nombre_valor", nullable=false)
    public String getNombreValor() {
        return this.nombreValor;
    }
    
    public void setNombreValor(String nombreValor) {
        this.nombreValor = nombreValor;
    }

    
    @Column(name="monto", precision=10)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }




}


