package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ValorRolloUnidad generated by hbm2java
 */
@Entity
@Table(name="valor_rollo_unidad"
    ,catalog="sigf_v1"
)
public class ValorRolloUnidad  implements java.io.Serializable {


     private Integer idValorRolloUnidad;
     private UnidadNegocio unidadNegocio;
     private int compra;
     private int venta;

    public ValorRolloUnidad() {
    }

    public ValorRolloUnidad(UnidadNegocio unidadNegocio, int compra, int venta) {
       this.unidadNegocio = unidadNegocio;
       this.compra = compra;
       this.venta = venta;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_valor_rollo_unidad", unique=true, nullable=false)
    public Integer getIdValorRolloUnidad() {
        return this.idValorRolloUnidad;
    }
    
    public void setIdValorRolloUnidad(Integer idValorRolloUnidad) {
        this.idValorRolloUnidad = idValorRolloUnidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_unidad", nullable=false)
    public UnidadNegocio getUnidadNegocio() {
        return this.unidadNegocio;
    }
    
    public void setUnidadNegocio(UnidadNegocio unidadNegocio) {
        this.unidadNegocio = unidadNegocio;
    }

    
    @Column(name="compra", nullable=false)
    public int getCompra() {
        return this.compra;
    }
    
    public void setCompra(int compra) {
        this.compra = compra;
    }

    
    @Column(name="venta", nullable=false)
    public int getVenta() {
        return this.venta;
    }
    
    public void setVenta(int venta) {
        this.venta = venta;
    }




}


