package com.areatecnica.sigf_v1.entities;
// Generated 31-08-2016 4:14:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VentaBoleto generated by hbm2java
 */
@Entity
@Table(name="venta_boleto"
    ,catalog="sigf_v1"
)
public class VentaBoleto  implements java.io.Serializable {


     private Integer idVentaBoleto;
     private Terminal terminal;
     private Date fechaVentaBoleto;
     private String nombreComprador;
     private int totalCompra;
     private Set<DetalleVentaBoleto> detalleVentaBoletos = new HashSet<DetalleVentaBoleto>(0);

    public VentaBoleto() {
    }

	
    public VentaBoleto(Terminal terminal, Date fechaVentaBoleto, String nombreComprador, int totalCompra) {
        this.terminal = terminal;
        this.fechaVentaBoleto = fechaVentaBoleto;
        this.nombreComprador = nombreComprador;
        this.totalCompra = totalCompra;
    }
    public VentaBoleto(Terminal terminal, Date fechaVentaBoleto, String nombreComprador, int totalCompra, Set<DetalleVentaBoleto> detalleVentaBoletos) {
       this.terminal = terminal;
       this.fechaVentaBoleto = fechaVentaBoleto;
       this.nombreComprador = nombreComprador;
       this.totalCompra = totalCompra;
       this.detalleVentaBoletos = detalleVentaBoletos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_venta_boleto", unique=true, nullable=false)
    public Integer getIdVentaBoleto() {
        return this.idVentaBoleto;
    }
    
    public void setIdVentaBoleto(Integer idVentaBoleto) {
        this.idVentaBoleto = idVentaBoleto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_terminal", nullable=false)
    public Terminal getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(Terminal terminal) {
        this.terminal = terminal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_venta_boleto", nullable=false, length=19)
    public Date getFechaVentaBoleto() {
        return this.fechaVentaBoleto;
    }
    
    public void setFechaVentaBoleto(Date fechaVentaBoleto) {
        this.fechaVentaBoleto = fechaVentaBoleto;
    }

    
    @Column(name="nombre_comprador", nullable=false, length=45)
    public String getNombreComprador() {
        return this.nombreComprador;
    }
    
    public void setNombreComprador(String nombreComprador) {
        this.nombreComprador = nombreComprador;
    }

    
    @Column(name="total_compra", nullable=false)
    public int getTotalCompra() {
        return this.totalCompra;
    }
    
    public void setTotalCompra(int totalCompra) {
        this.totalCompra = totalCompra;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ventaBoleto")
    public Set<DetalleVentaBoleto> getDetalleVentaBoletos() {
        return this.detalleVentaBoletos;
    }
    
    public void setDetalleVentaBoletos(Set<DetalleVentaBoleto> detalleVentaBoletos) {
        this.detalleVentaBoletos = detalleVentaBoletos;
    }




}


